### ISSUE TITLE
实际使用中如何判定目标跟丢？

### ISSUE THREAD

**Issue by JimmyLauren** [HonglinChu/SiamTrackers#102]
你好，请问Nanotrack在实际使用中要如何判定目标跟丢？然后跟丢目标要如何后续帧中找回？

**Comment by ZHULIII** [comment]
同问！！

**Comment by Tomhardy13** [comment]
我是通过best_score设置阈值过滤的

**Comment by liujianisme** [comment]
@Tomhardy13 这个score好像没有啥规律，我这边测试目标和非目标得分都很高，请问你那边是怎么解决的？

**Comment by 733ly** [comment]
我也想知道，他不管是不是目标得分都很高

**Comment by dengxiongshi** [comment]
> [@Tomhardy13](https://github.com/Tomhardy13) 这个score好像没有啥规律，我这边测试目标和非目标得分都很高，请问你那边是怎么解决的？
Hello! 请问解决了嘛😁
