### ISSUE TITLE
NanoTrackV3的训练数据集有哪些？

### ISSUE THREAD

**Issue by Z-Xiong** [HonglinChu/SiamTrackers#107]
我这边YouBB数据集下载不了，请问NanoTrackV3预训练模型使用了YoutuBB这个数据集训练了吗？

**Comment by fly-miao** [comment]
在nanotrack/models/config/configv3.yaml里有
DATASET: 
    NAMES: 
    - 'GOT'
    - 'VID'
    - 'YOUTUBEBB'
    - 'COCO'
    - 'DET'
    - 'LASOT'

**Comment by Z-Xiong** [comment]
配置文件里写的不一定是真实使用的

**Comment by fly-miao** [comment]
好的了解，看到你的id想起您之前一个项目是LightTrack转rknn在瑞芯微npu上部署的，不知道您是否还记得

**Comment by Z-Xiong** [comment]
是的，那个项目设置为私人仓库了。lighttrack的效果要比nanotrack要好，但是速度不是很快，没有训练代码，也不能进行QAT，混合量化后的精度不是很好。

**Comment by fly-miao** [comment]
我这边在参考那个项目和nanotrack在npu上的python部署做nanotrack在npu上的c++部署，但是后处理部分遇到一些问题，导致结果完全不对，不知您是否可以指点一二

**Comment by Z-Xiong** [comment]
可以的，转到我的https://github.com/Z-Xiong/LightTrack-ncnn项目下提issue吧

**Comment by fly-miao** [comment]
好的，谢谢

**Comment by HonglinChu** [comment]
> 

V2和V3都使用了6个数据集
