### ISSUE TITLE
大佬，请问IOU<?合适呢

### ISSUE THREAD

**Issue by lkw666** [HonglinChu/SiamTrackers#11]
在生成训练样本时，请问大神，iou设置为小于多少合适呢

**Comment by HonglinChu** [comment]
UpdateNet中生成模板的IoU可以设置选择0.2或者0.3；

**Comment by lkw666** [comment]
> UpdateNet中生成模板的IoU可以设置选择0.2或0.3；

嗯嗯，好嘞，大神，非常感谢

**Comment by xzy123456611** [comment]
> 在生成训练样本时，请问大神，iou设置为小于多少合适呢

你好，你训练2019的模型吗
