### ISSUE TITLE
关于Nanotrack特征融合的部分

### ISSUE THREAD

**Issue by Coder-TieHH** [HonglinChu/SiamTrackers#118]
请问一下博主，您的特征融合部分是借鉴的哪个网络，我转成onnx看之后有点乱，我看lighttrack好像融合的操作很简单啊。
![image](https://github.com/HonglinChu/SiamTrackers/assets/130418678/947fb18f-d00e-452a-a2c9-b358c04d0428)
![image](https://github.com/HonglinChu/SiamTrackers/assets/130418678/c9c57458-2eb3-45e2-857c-4f07365065c2)

**Comment by HonglinChu** [comment]
你看NanoTrackV2的网络结构，V3的特征融合确实复杂了点

**Comment by Coder-TieHH** [comment]
好的，非常感谢您的解答
