### ISSUE TITLE
如图，SiamFCpp-pysot和SiamFCpp-video_analyst都是SiamFC++的实现吗，具体模型参数是否一样，有没有区别

### ISSUE THREAD

**Issue by Jontyshaw** [HonglinChu/SiamTrackers#119]
![image](https://github.com/HonglinChu/SiamTrackers/assets/34794522/911dfd5d-3a83-49a1-8418-da54880fcad9)

**Comment by HonglinChu** [comment]
SiamFC++的话建议还是直接去看官方的源码，另外可以参考一下NanoTrackV2
