### ISSUE TITLE
nanotrack数据集got裁剪的问题

### ISSUE THREAD

**Issue by Coder-TieHH** [HonglinChu/SiamTrackers#120]
您好博主，想问一下您在训练之前将图片进行裁剪的问题，因为刚接触vot这块，这里的271以及511按照我看siamfc的理解，是对边界的扩展，但是为什么有两个值？这里的271以及511究竟用哪个裁剪过的大小进入训练。希望您能抽出时间，不吝赐教！🙏
![0d1496c557919232700d792cea9cfe8](https://github.com/HonglinChu/SiamTrackers/assets/130418678/5d5cdbf8-c7b9-477b-a9ca-b029e652a9ac)
![54236aa50aaa2c1e0b5df326aed4faa](https://github.com/HonglinChu/SiamTrackers/assets/130418678/34bbcb59-369e-4c79-b670-82bf054d0244)

**Comment by HonglinChu** [comment]
选择511大小

**Comment by Coder-TieHH** [comment]
好的，非常感谢
