### ISSUE TITLE
nanotrack v1复现问题

### ISSUE THREAD

**Issue by uefall** [HonglinChu/SiamTrackers#121]
nanotrack v1 在got10k上的0.604 | 0.724 这两个指标是只用got10k训练出来的吗？
我用基准的代码重新训练，只有0.5左右
代码的差异只有按照 #95 的[https://github.com/HonglinChu/SiamTrackers/issues/95#issuecomment-1521096781](url)修改了

还是有什么其他的设置需要对齐一下？
希望能得到解答，多谢！

**Comment by HonglinChu** [comment]
加载最好的模型作为预训练再重新训练微调一下效果会好很多

**Comment by uefall** [comment]
这个加载最好的模型是指？第一轮训练出来的模型吗？还有就是 crop 的 size 对训练是否有影响呢，因为看到 config 里写的和 crop 脚本里默认处理的并不一致。感谢指教

**Comment by HonglinChu** [comment]
运行的时候config里面的会覆盖掉默认的配置，以config为准。还有复现的时候可以看看nanotrackv2，多使用几个训练集精度比v1要好很多
