### ISSUE TITLE
nanotrack V3复现过程多数据集训练和got10训练效果一样？

### ISSUE THREAD

**Issue by Coder-TieHH** [HonglinChu/SiamTrackers#124]
博主您好，我我再复现您的V3版本的时候，将6个数据集都准备好了，但是为什么实际训练的时候，显示了数据集都加载成功了，但是感觉实际训练也只是用了got进行训练，希望您百忙之中能够抽出时间不吝赐教！🙏
![image](https://github.com/HonglinChu/SiamTrackers/assets/130418678/ec685699-1426-48fa-a482-55ea87c86bb5)
![image](https://github.com/HonglinChu/SiamTrackers/assets/130418678/ea94abb5-b7e1-473f-8c80-e7c78957ab16)

**Comment by Coder-TieHH** [comment]
我发现了是VIDEOS_PER_EPOCH这个参数的问题，请问这个参数如果像您一样选择6个数据集进行训练需要设置为多少，这个参数的意义是什么？

**Comment by HonglinChu** [comment]
VIDEOS_PER_EPOCH可以理解成是训练一个epoch使用到的图片对数量；使用的数据集种类越多，总的训练数据越大， VIDEOS_PER_EPOCH就要设置的越大，尽可能保证每一个epoch内，使用到的训练数据覆盖到所有不同数据集；我在训练NanoTrackV2 和V3的时候使用了6个数据集，VIDEOS_PER_EPOCH设置的是400000；当只使用GOT训练的时候，可以降低数值设置成100000或者200000

**Comment by Coder-TieHH** [comment]
好的，非常感谢您的解答，但是我实际复现的时候，以nanotrack3为例，当我VIDEOS_PER_EPOCH设置为400000时，最多在vot2018上eao只能到0.260左右，但是当我设置为1000000时能够到达0.417，请问您是如何训练的

**Comment by Coder-TieHH** [comment]
好的，感谢您的解答，但是为什么当我和您的参数设置一致时，训练出来的最后在vot2018上eao只有0.260左右，还是说需要用您提供的pretrain训练，这个pretraind是怎么拿到的呢，请您不吝赐教🙏
