### ISSUE TITLE
siamFC预训练模型

### ISSUE THREAD

**Issue by zyzqmm** [HonglinChu/SiamTrackers#126]
请问siamFC预训练模型 alexnet.pth在哪里下载？

**Comment by HonglinChu** [comment]
https://pan.baidu.com/s/1YA7JP14D3FG0FGthVNmIaw?pwd=r2c2 提取码: r2c2

**Comment by HonglinChu** [comment]
https://pan.baidu.com/s/1Xug00I6fVVH7X0_-SGuXtA?pwd=fidz 提取码: fidz

https://pan.baidu.com/s/1YA7JP14D3FG0FGthVNmIaw?pwd=r2c2 提取码: r2c2
