### ISSUE TITLE
NanoTrack train on custom dataset

### ISSUE THREAD

**Issue by ParaImage** [HonglinChu/SiamTrackers#127]
I want to train nanotrackers on my custom data but I dont know how generate json files of dataset.
please upload sample json files of got10k in google drive that I access to it.

**Comment by HonglinChu** [comment]
http://got-10k.aitestunion.com/downloads 
https://drive.google.com/file/d/1VwTAAiiT4gZVUVkoHSMV3vRJATrBSOIz/view?usp=drive_link
