### ISSUE TITLE
NanoTrack自定义数据集相关问题

### ISSUE THREAD

**Issue by MHGL** [HonglinChu/SiamTrackers#128]
# 使用场景
现需要对无人机进行跟踪，但是无人机成像大小一般在30像素左右，所以考虑是将exampler size调整为31，instance size调整为127，但是在这个过程中遇到一些问题，希望您能抽空指导一下。

# 问题1
在数据集裁剪过程中，有参数为271和511，请问这些参数设置依据在哪里？请给出相关链接或者出处。
# 问题2
在nanotrack/datasets/point_target.py中有如下代码：
```python
pos = np.where(np.square(tcx - points[0]) / np.square(tw / 4) +
                       np.square(tcy - points[1]) / np.square(th / 4) < 1)
```
我的理解是根据椭圆公式进行正负样本判断，可能是因为目标宽高不同，所以采用椭圆，但是为什么不采用tw / 2，而是使用tw / 4，这是什么原理？请给出参考链接或出处。

# 最后
非常期待您能抽时间指导一二，谢谢

**Comment by HonglinChu** [comment]
问题1： 
https://github.com/STVIR/pysot/tree/master/training_dataset/yt_bb 参考pysot官方的训练集裁剪方式，图像裁剪成511大小
问题2：
https://github.com/hqucv/siamban 官方代码，你也可以改变大小
另外，如果你是使用小目标跟踪，可以考虑多尺度特征融合，NanoTrack使用16倍下采样特征，你可以使用8倍or 4倍试试，那样的计算量会增大

**Comment by MHGL** [comment]
感谢您的指导
