### ISSUE TITLE
Cant train good!

### ISSUE THREAD

**Issue by ParaImage** [HonglinChu/SiamTrackers#131]
I trained nano tracker v1 on got10 using the default config file `configv1.yaml ` and tested the best model (after training) on VOT2018 and achieved the following results:
```
-------------------------------------------------------------
|Tracker Name | Accuracy | Robustness | Lost Number |  EAO  |
-------------------------------------------------------------
| nanotrackv1 |  0.359   |   1.105    |    236.0    | 0.121 |
-------------------------------------------------------------
```
My training hardware: 2 x RTX4090
I'm not sure why I couldn't achieve the EAO of nano tracker v1 as reported in https://github.com/HonglinChu/SiamTrackers/tree/master/NanoTrack? Any suggestion, hints will be highly appreciated. Thanks in advance.

**Comment by sezarxray** [comment]
I also saw this. training with you code result in poor metrics.(nanotrack)

**Comment by HonglinChu** [comment]
> I trained nano tracker v1 on got10 using the default config file `configv1.yaml ` and tested the best model (after training) on VOT2018 and achieved the following results:
> 
> ```
> -------------------------------------------------------------
> |Tracker Name | Accuracy | Robustness | Lost Number |  EAO  |
> -------------------------------------------------------------
> | nanotrackv1 |  0.359   |   1.105    |    236.0    | 0.121 |
> -------------------------------------------------------------
> ```
> 
> My training hardware: 2 x RTX4090 I'm not sure why I couldn't achieve the EAO of nano tracker v1 as reported in https://github.com/HonglinChu/SiamTrackers/tree/master/NanoTrack? Any suggestion, hints will be highly appreciated. Thanks in advance.

you can try to load the best model(EAO=0.121) as the pretrained model, and then to finetune it. For nanotrackv1 , we only use GOT dataset, for nanotrackv2 and v3, we use six datasets.
you can also refer https://github.com/HonglinChu/SiamTrackers/issues/125
