### ISSUE TITLE
Readme里面的数据，为啥和我在论文中看到的不一致

### ISSUE THREAD

**Issue by Coder-TieHH** [HonglinChu/SiamTrackers#133]
博主您好，又来打扰您了，最近在看论文，修改自己的模型，突然发先您的README里面的SiamTPN的vot2018的数据好像不对呀。
![image](https://github.com/HonglinChu/SiamTrackers/assets/130418678/5272345a-614b-4d59-8b22-5b7166f00637)
![image](https://github.com/HonglinChu/SiamTrackers/assets/130418678/e7f176e2-11b3-402f-943b-cf3f1510e79c)
还有一个问题是，siamAPN/APN++论文里面好像没有vot2018的数据，您是自己测的吗？
还请您不吝赐教，感谢！

**Comment by HonglinChu** [comment]
当时在VOT上关于SiamAPN, SiamTPN的EAO的值的确比较低,可能是我测试的时候配置参数有问题, 我在results里面也提供了所有算法的评估结果.  或者你可以重新跑一个SiamTPN来验证一下

**Comment by HonglinChu** [comment]
所有的算法都是自己重新配置在同一个环境下跑的, 当时在VOT上SiamAPN, SiamTPN的EAO的值的确比较低,我也不太相信,不过我使用的都是同一套参数, 它们在DTB和GOT上数值就比较高了, 可能是我测试的时候配置参数有问题. 另外我在results里面也提供了所有算法的评估结果. 或者你可以重新跑一个SiamTPN来验证一下;

**Comment by Coder-TieHH** [comment]
顺便再问您一个模型训练的问题，我自己的模型在训练之后，最后一段他的loss都会在0.2~0.3之间徘徊，还是波动还是挺大的，因为我跟着您的nanotrack进行训练的时候，发现最后的它都能降到0.1左右，这一点我在另一个issue也跟您说了。您说这个loss和最后的表现没有太大关系，但是我现在怀疑的是会不会说我最后接这一阶段它的波动有点大，它还没有完全收敛。您有什么建议吗？现在我的模型一阶段训练2018上eao有0.16左右。呃，我在训练您的nanotrack的时候，第一阶段差不多也能是也是一点几。但是第二阶段您的nanotrack，它是能够往上涨挺多的，大概一倍左右。但是我的模型呃就还是第二阶段finetune时候，他还是在这一阶就是0.2~0.3之间波动，涨点也几乎停滞了，您能给点建议吗😭😭

**Comment by Coder-TieHH** [comment]
顺便再问您一个模型训练的问题，我自己的模型在训练之后，最后一段他的loss都会在0.2~0.3之间徘徊，还是波动还是挺大的，因为我跟着您的nano track进行训练的时候，发现最后的它都能降到0.1左右，这一点我在另一个里面也跟您说了。您说这个loss和最后的表现没有太大关系，但是我现在怀疑的是会不会说我最后接这一阶段它的波动有点大，它还没有完全收敛。您有什么建议吗？现在我的模型一阶段训练2018上eao有0.16左右。呃，我在训练您的nanotrack的时候，第一阶段差不多也能是也是一点几。但是第二阶段您的nanotrack，它是能够往上涨挺多的，大概一倍左右。但是我的模型呃就还是第二阶段finetune时候，他还是在这一阶就是0.2~0.3之间波动，涨点也几乎停滞了，您能给点建议吗😭😭

**Comment by Coder-TieHH** [comment]
顺便再问您一个模型训练的问题，我自己的模型在训练之后，最后一段他的loss都会在0.2~0.3之间徘徊，还是波动还是挺大的，因为我跟着您的nano track进行训练的时候，发现最后的它都能降到0.1左右，这一点我在另一个issue也跟您说了。您说这个loss和最后的表现没有太大关系，但是我现在怀疑的是会不会说我最后接这一阶段它的波动有点大，它还没有完全收敛。您有什么建议吗？现在我的模型一阶段训练2018 的eao有0.16左右。呃，我在训练您的nanotrack的时候，第一阶段差不多也能是也是一点几。但是第二阶段您的nanotrack，它是能够往上涨挺多的，大概一倍左右。但是我的模型呃就还是第二阶段finetune时候，他还是在这一阶就是0.2~0.3之间波动，涨点也几乎停滞了，您能给点建议吗😭😭

**Comment by Coder-TieHH** [comment]
好的，我看看，感谢您的建议
