### ISSUE TITLE
直接测试demo.py时就报错该改哪里呢？

### ISSUE THREAD

**Issue by Guojiajing1** [HonglinChu/SiamTrackers#138]
Traceback (most recent call last):
  File "E:\Tools_project\python_project\DL\code\SiamTrackers-master\NanoTrack\bin\demo.py", line 142, in <module>
    main()
  File "E:\Tools_project\python_project\DL\code\SiamTrackers-master\NanoTrack\bin\demo.py", line 81, in main
    model = load_pretrain(model, args.snapshot).cuda().eval()
  File "E:\Tools_project\python_project\DL\code\SiamTrackers-master\NanoTrack\nanotrack\utils\model_load.py", line 71, in load_pretrain
    model.load_state_dict(pretrained_dict, strict=False)
  File "E:\Tools\Anacoda3\envs\py38\lib\site-packages\torch\nn\modules\module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ModelBuilder:
	size mismatch for ban_head.corr_pw_reg.conv_kernel.0.weight: copying a param with shape torch.Size([48, 48, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 1, 1]).
	size mismatch for ban_head.corr_pw_reg.conv_kernel.0.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_reg.conv_kernel.1.weight: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_reg.conv_kernel.1.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_reg.conv_kernel.1.running_mean: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_reg.conv_kernel.1.running_var: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_reg.conv_search.0.weight: copying a param with shape torch.Size([48, 48, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 1, 1]).
	size mismatch for ban_head.corr_pw_reg.conv_search.0.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_reg.conv_search.1.weight: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_reg.conv_search.1.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_reg.conv_search.1.running_mean: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_reg.conv_search.1.running_var: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_cls.conv_kernel.0.weight: copying a param with shape torch.Size([48, 48, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 1, 1]).
	size mismatch for ban_head.corr_pw_cls.conv_kernel.0.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_cls.conv_kernel.1.weight: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_cls.conv_kernel.1.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_cls.conv_kernel.1.running_mean: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_cls.conv_kernel.1.running_var: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_cls.conv_search.0.weight: copying a param with shape torch.Size([48, 48, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 1, 1]).
	size mismatch for ban_head.corr_pw_cls.conv_search.0.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_cls.conv_search.1.weight: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_cls.conv_search.1.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_cls.conv_search.1.running_mean: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.corr_pw_cls.conv_search.1.running_var: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([64]).
	size mismatch for ban_head.bbox_pred.0.weight: copying a param with shape torch.Size([4, 96, 1, 1]) from checkpoint, the shape in current model is torch.Size([4, 64, 1, 1]).

**Comment by Michaelzeyong** [comment]
请问如何修改的呀？
