### ISSUE TITLE
数据集下载

### ISSUE THREAD

**Issue by lewisli66** [HonglinChu/SiamTrackers#14]
学长，您好。readme里百度网盘的数据集，打不开，无法下载。可以重新分享下吗。UAV123 BaiduYun password: 2iq4

VOT2018 BaiduYun password: e5eh

十分感激，谢谢学长

**Comment by HonglinChu** [comment]
我刚才试过，可以打开的

**Comment by lewisli66** [comment]
谢谢学长，可以了。
