### ISSUE TITLE
NanotrackV2和V3重新训练后跟踪框不稳定，漂移

### ISSUE THREAD

**Issue by DragonGongY** [HonglinChu/SiamTrackers#143]
使用got-10k的数据集重新训练V2和V3后，跟踪时跟踪框不能框住目标物体，这里有几个问题想请教一下：
1.通过par_crop.py将图像处理成511时，发现图像被缩小很多，图像四周有很大片的区域都是黑色填充的，这样会不会影响算法的训练，直接按照最长边缩放，最短边填充是否效果会好一些。
2.训练时只改了这个参数，
![image](https://github.com/HonglinChu/SiamTrackers/assets/29235462/a98e06c9-924d-4c4a-a27d-93f697742d06)
其他参数保持原始的，训练完后模型跟踪的框不稳定，是否是图像crop的引起，不吝赐教

**Comment by HonglinChu** [comment]
因为backbone分类模型的特征不适用目标跟踪，第一次训练效果不能达到最好，需要多阶段训练，可以参考
https://github.com/HonglinChu/SiamTrackers/issues/125
