### ISSUE TITLE
关于Siamese tracker的搜参

### ISSUE THREAD

**Issue by dlivxpr** [HonglinChu/SiamTrackers#146]
在SiamBAN以及其他许多Siamese追踪器官方代码中都公布了tune.py。关于tune.py里选定的checkpoint是如何选择的，直接选择20还是训练完先测试11-20之间所有的checkpoint，选择最佳的checkpoint。对于不同数据集搜参选用的checkpoint是否都是选择同一个，还是有其他策略呢

**Comment by HonglinChu** [comment]
follow this https://github.com/HonglinChu/SiamTrackers/blob/master/NanoTrack/bin/hp_search.py
