### ISSUE TITLE
How the nanotrack onnx files works without opencv

### ISSUE THREAD

**Issue by jozapa** [HonglinChu/SiamTrackers#152]
Hi, I am trying to implement  nano tracker with the onnx files. I don´t understand the inputs and outputs of the onnx files to make an implementation without opencv tracker functions.

**Comment by HonglinChu** [comment]
I am sorry，we didn't provide the onnx inference code. you should do it by yourself. But, we provide the ncnn inference code
https://github.com/HonglinChu/NanoTrack/tree/master/ncnn_macos_nanotrack
