### ISSUE TITLE
可否提供更多实验的backbone的预训练权重？

### ISSUE THREAD

**Issue by TheodorePTP** [HonglinChu/SiamTrackers#154]
可否开源更多实验用到的backbone的预训练权重？如AlexNet、ShuffleNetV2。感谢回复，辛苦作者。

**Comment by HonglinChu** [comment]
We also try to use other backbone (e.g, shufflenetv2, mobilev2)， but the results are not better than mobilenetv3

**Comment by TheodorePTP** [comment]
> We also try to use other backbone (e.g, shufflenetv2, mobilev2)， but the results are not better than mobilenetv3
感谢作者回复。在更换backbone的时候，backbone的预训练权重是否是在imagesnet上训练得到的？你们是如何获得backbone的预训练权重的呢？

**Comment by HonglinChu** [comment]
Hi, you can get from here https://github.com/d-li14/mobilenetv3.pytorch
