### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by fairysli** [HonglinChu/SiamTrackers#157]
why "ValueError: max() arg is an empty sequence"?

**Comment by HonglinChu** [comment]
please provide more information

**Comment by fairysli** [comment]
![output](https://github.com/HonglinChu/SiamTrackers/assets/149767343/2a2dc3f9-3e42-4f6d-92df-23a4caf0ff94)
就是出现了这个错误，然后results文件里有结果
![微信截图_20240617112633](https://github.com/HonglinChu/SiamTrackers/assets/149767343/cc94539d-de54-42c9-9c33-4cc4d1748055)

**Comment by fairysli** [comment]
大佬，我还想问一下，能否在昇腾上实现推理？有没有相关参考资料吗？感谢感谢！！

**Comment by HonglinChu** [comment]
It seems that you get the final results, you can try this
python ./bin/eval.py

**Comment by fairysli** [comment]
非常感谢！我去试一下

**Comment by fairysli** [comment]
> It seems that you get the final results, you can try this python ./bin/eval.py

不行啊，还是同样的错误
![微信截图_20240619164327](https://github.com/HonglinChu/SiamTrackers/assets/149767343/154e27e9-5b18-4000-8b1a-ac7d7426cf71)

**Comment by xc153** [comment]
请问有解决吗

**Comment by fairysli** [comment]
> 请问有解决吗

没有，我直接检测了，检测结果挺好的

**Comment by fairysli** [comment]
> 大佬，我还想问一下，能否在昇腾上实现推理？有没有相关参考资料吗？感谢感谢！！

在昇腾芯片上可以实现，效果很好！

**Comment by HonglinChu** [comment]
https://blog.csdn.net/qq_58248345/article/details/135825911
