### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by abdulbhutta** [HonglinChu/SiamTrackers#158]
Hi,

I am trying to train the model with the GOT dataset, but I have a problem. What can I do to fix this? Please see the screenshot! 

Thanks!

<img width="999" alt="Screenshot 2024-06-28 at 6 43 52 PM" src="https://github.com/HonglinChu/SiamTrackers/assets/74075547/1bd2a51d-7b3a-4c88-bb3c-7b0b06e8a88b">

**Comment by David-vsr** [comment]
how did you fix that? :\
