### ISSUE TITLE
关于youtubebb原始数据集下载链接

### ISSUE THREAD

**Issue by 1085052159** [HonglinChu/SiamTrackers#16]
大佬您好，请问有没有Youtubebb原始数据集的百度云下载链接

**Comment by HonglinChu** [comment]
没有呢，原始数据集太大了，搞不下来


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HonglinChu/SiamTrackers"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月15日(星期四) 晚上6:46
收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HonglinChu/SiamTrackers] 关于youtubebb原始数据集下载链接 (#16)





 
大佬您好，请问有没有Youtubebb原始数据集的百度云下载链接

**Comment by 1085052159** [comment]
好吧，感谢大佬的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HonglinChu/SiamTrackers"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月19日(星期一) 下午3:57
收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;;
抄送:&nbsp;"冰"<1085052159@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HonglinChu/SiamTrackers] 关于youtubebb原始数据集下载链接 (#16)





 没有呢，原始数据集太大了，搞不下来 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "HonglinChu/SiamTrackers"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年10月15日(星期四) 晚上6:46 
 收件人:&amp;nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[HonglinChu/SiamTrackers] 关于youtubebb原始数据集下载链接 (#16) 
 
 
 
 
 
   
 大佬您好，请问有没有Youtubebb原始数据集的百度云下载链接
