### ISSUE TITLE
NanotrackV3 issue

### ISSUE THREAD

**Issue by nikolajovickg** [HonglinChu/SiamTrackers#169]
你好，我正在尝试通过 ONNX 整合跟踪器(tracker)，但遇到了输入维度(input dimensions)的问题。V3骨干网络(backbone)的输出形状为1x96x16x16的张量，而neckhead需要两个输入，分别为 1x96x16x16和 1x96x8x8.。我该如何调整骨干网络的输出以满足第二个输入的要求？我应该修改或删除哪些参数？我注意到在原始实现中，主干输入可以从 255x255 缩小到 127x127，但在 ONNXRuntime 中无法实现。这种情况下，我应该考虑填充图像、截断主干的输出、选择输出的特定部分，还是使用其他方法来处理这个不匹配？

**Comment by nikolajovickg** [comment]
Hello, I think I resolved it (input shape of the initial backbone inference is 255x255, for updated is 127x127).

**Comment by nikolajovickg** [comment]
changed input params for the backbone from 1x3x255x255 to symbolic 1x3xNxN, and output from 1x96x16x16 to 1x96xMxM and it works now well (it outputs 1x96x8x8 for 1x3x127x127 and 1x96x16x16 for 1x3x255x255)

**Comment by nikolajovickg** [comment]
changed input params for the backbone from 1x3x255x255 to symbolic 1x3xNxN, and output from 1x96x16x16 to 1x96xMxM and it works now well (it outputs 1x96x8x8 for 1x3x127x127 and 1x96x16x16 for 1x3x255x255)

**Comment by ret7020** [comment]
Hello! Do you have complete onnx inference working demo with postprocessing?

**Comment by Lucass9527** [comment]
你好，你解决这个问题了吗？我尝试重新转换整个模型成一个完整的onnx，这样进行部署。

> changed input params for the backbone from 1x3x255x255 to symbolic 1x3xNxN, and output from 1x96x16x16 to 1x96xMxM and it works now well (it outputs 1x96x8x8 for 1x3x127x127 and 1x96x16x16 for 1x3x255x255)将骨干网的输入参数从 1x3x255x255 改为符号化的 1x3xNxN，并将输出从 1x96x16x16 改为 1x96xMxM，现在运行良好（对于 1x3x127x127，输出为 1x96x8x8；对于 1x3x255x255，输出为 1x96x16x16）。
