### ISSUE TITLE
数据集迁移的问题

### ISSUE THREAD

**Issue by hby1997** [HonglinChu/SiamTrackers#19]
请问如何实现迁移到自己的数据集上呢？

**Comment by HonglinChu** [comment]
你的数据集是用来训练的还是用来测试的呢？ 如果用自己的数据集测试，建议可以把数据制作成OTB2015那样的，具体可以参考OTB2015的数据集格式；如果你想用自己的数据来训练模型，那就比较麻烦，建议参考商汤开源的算法simrpn++（pysot）中的生成训练数据集部分，生成crop511大小的文件&nbsp;https://github.com/STVIR/pysot/tree/master/training_dataset


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HonglinChu/SiamTrackers"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 晚上8:23
收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HonglinChu/SiamTrackers] 数据集迁移的问题 (#19)





 
请问如何实现迁移到自己的数据集上呢？

**Comment by PSKong** [comment]
我也有同样的问题，我是使用的siamfc 然后正在将数据制作成got-10k 形式但是运行后显示迭代次数过多
RecursionError: maximum recursion depth exceeded in comparison
请问这个问题应该如何解决呢？

**Comment by chaochaozouzou** [comment]
请问可以出一个训练custom data的指导文档么？
