### ISSUE TITLE
SiamFC-VID问题

### ISSUE THREAD

**Issue by ShiLongCheng** [HonglinChu/SiamTrackers#21]
您好，感谢您收集的代码，对我帮助很大。我运行了SiamFC-VID里面的代码，下面是一些问题，希望您能解答。
1. 我从百度云盘上下载了您提供的siamfc_30.pth预训练模型，当我运行 my_test.py后，程序可以运行，但是和您README.md里面提供的accuracy和precision完全不同，性能非常差，只有0.1多。
2. 当我运行可视化程序查看OTB100中每个视频的跟踪结果时，发现跟踪结果非常差，完全漂移了，并且bbox非常大。如下图所示：
![Snipaste_2020-12-04_15-27-25](https://user-images.githubusercontent.com/38320388/101134423-4f89b400-3645-11eb-9671-e55b4914b824.png)
3. 我运行SiamFC-GOT时，效果挺好的，基本和您提供的README.md一样

**Comment by ShiLongCheng** [comment]
我明白了。在tracker.py里面这样改就行了。^-^
`# box = (self.pos[0] - self.target_sz[0]/2 + 1, # xmin   convert to 1-based
        #          self.pos[1] - self.target_sz[1]/2 + 1, # ymin
        #          self.pos[0] + self.target_sz[0]/2 + 1, # xmax
        #          self.pos[1] + self.target_sz[1]/2 + 1) # ymax
        #x,y,w,h   # top-left  w,h

        box=np.array([
           self.pos[0] + 1 - (self.target_sz[0]) / 2,
           self.pos[1] + 1 - (self.target_sz[1]) / 2,
           self.target_sz[0], self.target_sz[1]])`

**Comment by HonglinChu** [comment]
解决了就好，前几天回老家了，没有网络。 SiamFC-VID效果不好，建议直接看SiamFC-GOT版本，另外，我早期提供的SiamFC的GOT版本在OTB，VOT16和VOT18的效果都和matlab版本的siamfc比较接近。目前我github上的SiamFC-GOT只是在OTB上效果最好，但是在VOT上效果一般。 建议你再自己重新训练一下siamfc，训练的时候注意设置batch=8，使用单GPU训练，否则训练效果会很差


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HonglinChu/SiamTrackers"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月4日(星期五) 下午4:04
收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [HonglinChu/SiamTrackers] SiamFC-VID问题 (#21)





 
我明白了。在tracker.py里面这样改就行了。^-^
 `# box = (self.pos[0] - self.target_sz[0]/2 + 1, # xmin   convert to 1-based
 #          self.pos[1] - self.target_sz[1]/2 + 1, # ymin
 #          self.pos[0] + self.target_sz[0]/2 + 1, # xmax
 #          self.pos[1] + self.target_sz[1]/2 + 1) # ymax
 #x,y,w,h   # top-left  w,h
     box=np.array([        self.pos[0] + 1 - (self.target_sz[0]) / 2,        self.pos[1] + 1 - (self.target_sz[1]) / 2,        self.target_sz[0], self.target_sz[1]])`
