### ISSUE TITLE
GlobalTrack of AAAI-20

### ISSUE THREAD

**Issue by yangjiangeyjg** [HonglinChu/SiamTrackers#22]
Thank you for sharing and i'd like to ask if 2020 AAAI's global track will be shared.
（GlobalTrack: A Simple and Strong Baseline for Long-Term Tracking）

**Comment by HonglinChu** [comment]
The speed of GlobalTrack is not ideal, so it is not added to the SiamTrackers project

**Comment by yangjiangeyjg** [comment]
> 
> 
> The speed of GlobalTrack is not ideal, so it is not added to the SiamTrackers project



> 
> 
> The speed of GlobalTrack is not ideal, so it is not added to the SiamTrackers project

**Comment by yangjiangeyjg** [comment]
> 
> 
> The speed of GlobalTrack is not ideal, so it is not added to the SiamTrackers project

OK,thanks.
