### ISSUE TITLE
关于siamfc

### ISSUE THREAD

**Issue by downeycheung** [HonglinChu/SiamTrackers#23]
用alexnet训练后，在otb和vot2018上进行测试，然后改成resnet22训练，再在otb和vot2018上测试，得到的结果没有变，一个数字都没变，这是为什么。

**Comment by HonglinChu** [comment]
你是模型加载错了吧。alexnet的那个模型建议自己重新训练一下，我自己训练的没有调参，在otb测试很好，但是在vot18上一般，比论文低了两个点。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhangfangbin"<notifications@github.com&gt;; 
发送时间: 2020年12月12日(星期六) 中午12:21
收件人: "HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [HonglinChu/SiamTrackers] 关于siamfc (#23)





 
用alexnet训练后，在otb和vot2018上进行测试，然后改成resnet22训练，再在otb和vot2018上测试，得到的结果没有变，一个数字都没变，这是为什么。

**Comment by mrq1102094712** [comment]
class SiamFCTransforms(object):

    def __init__(self, exemplar_sz=127, instance_sz=255, context=0.5):
        self.exemplar_sz = exemplar_sz
        self.instance_sz = instance_sz
        self.context = context 

        self.transforms_z = Compose([
            RandomStretch(),
            CenterCrop(instance_sz - 8),      #255-8
            RandomCrop(instance_sz - 2 * 8),  #255-16
            CenterCrop(exemplar_sz),          #127
            ToTensor()])
        self.transforms_x = Compose([
            RandomStretch(),
            CenterCrop(instance_sz - 8),    # 247
            RandomCrop(instance_sz - 2 * 8),  #239
            ToTensor()])


请问fc在训练时对于搜索分支x为什么不crop成 255x255 的，而是使用 239x239 的大小，这也导致搜索分支输出20x20 以及最后的得分图大小不是 17x17，而是15x15？

**Comment by HonglinChu** [comment]
这个你也可以改成255x255的试试，instance-sz是255大小，随机裁剪之就是255-8*2=239。我的理解是这里主要是为了进一步增强泛化能力。你也可以不进行这个操作进行对比，毕竟是非官方代码，不一定和原文一致的。

**Comment by HonglinChu** [comment]
> 用alexnet训练后，在otb和vot2018上进行测试，然后改成resnet22训练，再在otb和vot2018上测试，得到的结果没有变，一个数字都没变，这是为什么。
