### ISSUE TITLE
关于siamfcpp的训练速度

### ISSUE THREAD

**Issue by iminfine** [HonglinChu/SiamTrackers#25]
同学，你用siamfcpp官方代码训练过吗？我用一片V100在got10k上训练，速度感人，一个epoch要10个小时。你写的代码训练速度是怎样的？

**Comment by HonglinChu** [comment]
双卡大概45分钟一个epoch


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HonglinChu/SiamTrackers"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月15日(星期二) 中午11:46
收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HonglinChu/SiamTrackers] 关于siamfcpp的训练速度 (#25)





 
同学，你用siamfcpp官方代码训练过吗？我用一片V100在got10k上训练，速度感人，一个epoch要10个小时。你写的代码训练速度是怎样的？
