### ISSUE TITLE
学长，有没有训练好的SiameseFC模型呢

### ISSUE THREAD

**Issue by honeypro123** [HonglinChu/SiamTrackers#28]
学长，有没有训练好的SiameseFC模型呢

**Comment by HonglinChu** [comment]
已经提供了百度云下载链接

**Comment by lc0716** [comment]
请问有没有ResNet22在SiameseFC上的预训练权重文件呢？

**Comment by HonglinChu** [comment]
这个没有的，我视频讲了，那个代码仅仅提供参考的，另外resnet22和fc以及rpn的结合效果并不是非常好，学一下原理就好了，还是赶紧进去学anchor-free的跟踪算法吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月15日(星期四) 下午2:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HonglinChu/SiamTrackers] 学长，有没有训练好的SiameseFC模型呢 (#28)





 
请问有没有ResNet22在SiameseFC上的预训练权重文件呢？
