### ISSUE TITLE
DaSiamRPN测试效果问题

### ISSUE THREAD

**Issue by ShiLongCheng** [HonglinChu/SiamTrackers#29]
您好，我又发现一个问题。我用DaSiamRPN-GOT加载官方提供的SiamRPNBIG.model，测试OTB2015结果为：
`prec_score:0.840 -succ_score:0.634 -succ_rate:0.824`。用UpdateNet（选择的step=1）加载SiamRPNBIG.model测试OTB2015结果为：`prec_score:0.853 -succ_score:0.641 -succ_rate:0.830`。这两个结果不一样，而且低于SiamR-CNN论文中提供的DaSiamRPN评测结果（prec:0.878, succ:0.658）。请问您知道是怎么回事吗？在VOT2018上测试DaSiamRPN结果为acc: 0.586, eao:0.383这个结果还算正常。

**Comment by HonglinChu** [comment]
以VOT2018为准，官方提供的DaSiamRPN 加载BIGmodel就是0.383，

**Comment by ShiLongCheng** [comment]
> 以VOT2018为准，官方提供的DaSiamRPN 加载BIGmodel就是0.383，

看到您这么晚还回复我信息真的很感激，不好意思耽误您的时间了-_-。我最近想基于这些算法改进，写小论文，但是效果一直复现不出来，感觉这些算法都不太好复现，不是精度不够，就是越训练越差。^-^

**Comment by HonglinChu** [comment]
我github上，siamfc-got，siamrpnpp-up-got（siamrpn），siamrpnpp-dw-got（siamrpn++ alexnet）都是可复现了，也提供了模型。可以直接用





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HonglinChu/SiamTrackers"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月29日(星期二) 上午10:54
收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;;
抄送:&nbsp;"SmallLion🦁️"<1628464345@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [HonglinChu/SiamTrackers] DaSiamRPN测试效果问题 (#29)





  
以VOT2018为准，官方提供的DaSiamRPN 加载BIGmodel就是0.383，
  
看到您这么晚还回复我信息真的很感激，不好意思耽误您的时间了-_-。我最近想基于这些算法改进，写小论文，但是效果一直复现不出来，感觉这些算法都不太好复现，不是精度不够，就是越训练越差。^-^

**Comment by ShiLongCheng** [comment]
> 我github上，siamfc-got，siamrpnpp-up-got（siamrpn），siamrpnpp-dw-got（siamrpn++ alexnet）都是可复现了，也提供了模型。可以直接用
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "HonglinChu/SiamTrackers" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月29日(星期二) 上午10:54 收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 抄送:&nbsp;"SmallLion🦁️"<1628464345@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [HonglinChu/SiamTrackers] DaSiamRPN测试效果问题 (#29) 以VOT2018为准，官方提供的DaSiamRPN 加载BIGmodel就是0.383， 看到您这么晚还回复我信息真的很感激，不好意思耽误您的时间了-_-。我最近想基于这些算法改进，写小论文，但是效果一直复现不出来，感觉这些算法都不太好复现，不是精度不够，就是越训练越差。^-^ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢，感谢，感谢。那些复现不出来的，有可能是哪些地方出问题了呢？

**Comment by HonglinChu** [comment]
UpdateNet也提供了完整的代码和训练的每一个阶段的模型（VOT2018上的）。DaSiamRPN一定要在python3环境下测试，论文中的许多trick，比如全局搜索策略在开源代码中并没有体现，所以DaSiamRPN的训练建议还是不要搞了。可以简单把DaSiamRPN理解成通道由256变成了512。
