### ISSUE TITLE
在VOT2018是怎么复现到原文的？难道调不同阶段的学习率？？

### ISSUE THREAD

**Issue by wangaixue** [HonglinChu/SiamTrackers#3]

**Comment by HonglinChu** [comment]
是的呢，对学习率比较敏感

**Comment by wangaixue** [comment]
@HonglinChu 作者 整理的很好啊 棒棒棒  其余的 代码 什么时候上传呢？？

**Comment by HonglinChu** [comment]
一直回不去学校,剩下的数据比较大暂时传不了

**Comment by wangaixue** [comment]
@HonglinChu 能百度云发一份学习一下吗 哈哈

**Comment by HonglinChu** [comment]
> 一直回不去学校,剩下的数据比较大暂时传不了

最近被别的事情耽搁了, 数据集太大了,可以加群讨论哈

**Comment by wangaixue** [comment]
@HonglinChu  已经加啦

**Comment by CVUsers** [comment]
@HonglinChu @wangaixue @zihaomu  请问一下，加个wx，或者群，交流一下，有个追踪瓶颈问题讨论，如遮挡
