### ISSUE TITLE
siamFCpp  got10k在训练之前需要先裁剪好吗？

### ISSUE THREAD

**Issue by zh-mi** [HonglinChu/SiamTrackers#30]
师兄您好，在训练之前需要先裁剪好GOT10K数据集吗，如果直接用原始的数据集训练，是不是对cpu负担很大，导致最后GPU跑不起来

**Comment by HonglinChu** [comment]
siamfcpp使用GOT训练不需要提前裁剪，它是在线裁剪的，加载原始图片然后裁剪，再送入模型进行训练。旷视开源的代码也是这么操作的，因为读取的是原始图片，所以训练速度整体上会慢一点，但是不会影响太大。只有siamrpnpp的代码需要裁剪，对got离线裁剪511大小，训练的时候读取的是已经裁剪好的数据。

**Comment by zh-mi** [comment]
谢谢博主的回答，我在复现SiamFCpp中的出现了以下的警告
![image](https://user-images.githubusercontent.com/55775401/103354156-bf287d00-4ae5-11eb-8e3f-364325b7e0ec.png)
警告：有些模型参数不在检查点中，这是模型的原因还是程序的原因啊，我模型是在官网上下载的

**Comment by zh-mi** [comment]
不知道是不是这个原因导致我的训练变得很慢

**Comment by HonglinChu** [comment]
官方的不清楚，我提供了修改之后的代码和预训练模型以及训练好的模型
