### ISSUE TITLE
SiamRPN++的复现结果

### ISSUE THREAD

**Issue by 1085052159** [HonglinChu/SiamTrackers#31]
大佬您好，我看到你的rpn++复现的结果也不太好，您后面有没有尝试复现出原效果

**Comment by HonglinChu** [comment]
我复现的是alexnet版本的siamrpnpp, 使用了四个训练集,并没有调参,这个复现结果不可能和官方完全一样的,但是效果和官方的已经很接近了,调参肯定能调上去的.

**Comment by HonglinChu** [comment]
> 大佬您好，我看到你的rpn++复现的结果也不太好，您后面有没有尝试复现出原效果

我复现的是alexnet版本的siamrpnpp, 使用了四个训练集,并没有调参, 调参之后效果应该会更好一些

**Comment by 1085052159** [comment]
> > 大佬您好，我看到你的rpn++复现的结果也不太好，您后面有没有尝试复现出原效果
> 
> 我复现的是alexnet版本的siamrpnpp, 使用了四个训练集,并没有调参, 调参之后效果应该会更好一些

您用的是原版参数吗？您的机器配置是啥，8卡还是

**Comment by HonglinChu** [comment]
双卡1080, 代码都在对应目录里面可以找到,参数一般都是默认,

**Comment by 1085052159** [comment]
> 双卡1080, 代码都在对应目录里面可以找到,参数一般都是默认,

那您训练了多久

**Comment by HonglinChu** [comment]
B站对应的视频应该都有说明

**Comment by HonglinChu** [comment]
> > 双卡1080, 代码都在对应目录里面可以找到,参数一般都是默认,
> 
> 那您训练了多久

三天三夜

**Comment by HonglinChu** [comment]
> > 双卡1080, 代码都在对应目录里面可以找到,参数一般都是默认,
> 
> 那您训练了多久

72个小时左右

**Comment by 1085052159** [comment]
> > > 双卡1080, 代码都在对应目录里面可以找到,参数一般都是默认,
> > 
> > 
> > 那您训练了多久
> 
> 72个小时左右

那我要是复现rpn++，不得要训练一个星期
