### ISSUE TITLE
GOT10k数据集中visible ratios的计算方式？

### ISSUE THREAD

**Issue by codylcs** [HonglinChu/SiamTrackers#32]
林林大佬您好，GOT10K数据集中提供了visible ratios，请教下您，这个visible ratios是怎么计算得到的？论文中只看到这句相关的The regions that are occluded or truncated by image boundary correspond to the invisible parts，麻烦您给指导下？不胜感激

**Comment by HonglinChu** [comment]
我认为这个博客的图展示的比较好：https://blog.csdn.net/xwmwanjy666/article/details/98939868；这个就是和遮挡比例有关，GOT对遮挡视频按照遮挡的百分比进行了划分。像OTB，VOT这些数据集对遮挡视频属性的划分标准有：全遮挡和部分遮挡划分的比较粗糙，相比之下，GOT对遮挡程度划分的更细一些。

**Comment by codylcs** [comment]
感谢回复，链接已经失效，其实就是想了解GOT10k怎么细分遮挡比例的，目测的还是有特殊的计算方式？

**Comment by HonglinChu** [comment]
（1）之前尝试通过稀疏子空间跟踪算法对遮挡视频计算遮挡率，当目标形变不大的情况计算还是很合理的，形变很大背景杂乱就会导致遮挡计算误差很大。（2）通过对40多个遮挡视频采用目测的方式进行手动标注遮挡程度，标注了一天，也只能大概区分轻微遮挡（<20%），中等遮挡（20%~50%），严重遮挡（50～99%），完全遮挡（100%）这四种程度，仍然很粗糙，显然官方应该不是用的目测方法，哈哈哈
