### ISSUE TITLE
SiamFC-GOT 训练出现

### ISSUE THREAD

**Issue by 1071189147** [HonglinChu/SiamTrackers#33]
您好，我下载了部分GOT 数据，看能不能跑通代码，结果运行出来这样的结果，后面就结束了，没有报epoch  loss 等，
![1611716451(1) (1)](https://user-images.githubusercontent.com/28439235/105937234-1ba09d00-6090-11eb-80b9-1b4573ed0da1.png)
请问这是哪里出现问题了，在代码里定位不到这一块

**Comment by HonglinChu** [comment]
看不到你上传的图片

**Comment by 1071189147** [comment]
您好，感谢您的解答，图片中的内容如下：
[2021-01-27 11:00:26,192][tracker.py][line:237][INFO] start training!
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]
0it [00:00, ?it/s]



后面都是这样，没有其他，就直接结束了，




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "linlin"<notifications@github.com&gt;; 
发送时间: 2021年1月27日(星期三) 中午11:17
收件人: "HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 
抄送: "wxl"<1071189147@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [HonglinChu/SiamTrackers] SiamFC-GOT 训练出现 (#33)





 
看不到你上传的图片

**Comment by HonglinChu** [comment]
我从给的信息看不来问题，vscode单不调试看看，建议你还是把所有的数据都下载下来训练吧，毕竟json文件包含了所有的视频序列，你只使用一部分可能导致一些数据加载不到

**Comment by 1071189147** [comment]
好的，感谢解答，我再尝试一下，如果最后找到问题了或者放弃了，我会关闭这个





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HonglinChu/SiamTrackers"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月27日(星期三) 中午11:29
收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;;
抄送:&nbsp;"wxl"<1071189147@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HonglinChu/SiamTrackers] SiamFC-GOT 训练出现 (#33)





 
我从给的信息看不来问题，vscode单不调试看看，建议你还是把所有的数据都下载下来训练吧，毕竟json文件包含了所有的视频序列，你只使用一部分可能导致一些数据加载不到
