### ISSUE TITLE
关于使用got10k工具评估VOT

### ISSUE THREAD

**Issue by yangjiangeyjg** [HonglinChu/SiamTrackers#34]
作者您好，我想问下使用got10K工具评估VOT数据集会报错吗？
我是报了一个除零错，就是在对iou除去NaN数据后做平均的时候，请问这个您解决了吗？

**Comment by HonglinChu** [comment]
很久之前测试过，GOT工具箱测试VOT不能计算EAO，不建议用got工具箱测试vot，建议你直接用pysot-toolkit，pysot代码里面可以直接查看，对otb和vot测试都支持

**Comment by yangjiangeyjg** [comment]
> 
> 
> 很久之前测试过，GOT工具箱测试VOT不能计算EAO，不建议用got工具箱测试vot，建议你直接用pysot-toolkit，pysot代码里面可以直接查看，对otb和vot测试都支持

好的谢谢
