### ISSUE TITLE
Many wrong annotated bbox in GOT10K dataset

### ISSUE THREAD

**Issue by cxlldhty** [HonglinChu/SiamTrackers#35]
Why there are too many wrong annotated bbox for GOT10K dataset? For example, GOT-10k_Train_009058 sequence.

**Comment by HonglinChu** [comment]
you can try this https://github.com/arbitularov/SiamRPN-PyTorch/blob/master/fixed.py
if w<=0 or h<=0, the box is wrong, so it should be removed.

**Comment by cxlldhty** [comment]
> you can try this https://github.com/arbitularov/SiamRPN-PyTorch/blob/master/fixed.py
> if w<=0 or h<=0, the box is wrong, so it should be removed.

Thanks, this link confirms that GOT10K does have many wrong annotations.
