### ISSUE TITLE
got10k测试结果无法在官网上评估

### ISSUE THREAD

**Issue by zh-mi** [HonglinChu/SiamTrackers#36]
学长，我按照siamFCpp源码训练之后测试了一下，然后将测试得到的.zip文件放到got10官网上评测，却不出结果，格式完全跟他给的fc实例一样，这种情况你有了解，有什么解决办法吗？？
![image](https://user-images.githubusercontent.com/55775401/115717576-e2d14500-a3ac-11eb-81e4-38ec3c0b170c.png)
![image](https://user-images.githubusercontent.com/55775401/115717707-03010400-a3ad-11eb-9ffa-3e6a19798908.png)

![image](https://user-images.githubusercontent.com/55775401/115717708-03010400-a3ad-11eb-89a9-acc054892870.png)

**Comment by HonglinChu** [comment]
这个问题私聊我邮箱

**Comment by EnthusiasticZ** [comment]
我也遇到了同样的情况，学长可以帮助一下吗

**Comment by zh-mi** [comment]
我当初是下载的数据集破坏了导致无法评估




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HonglinChu/SiamTrackers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月28日(星期二) 晚上8:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HonglinChu/SiamTrackers] got10k测试结果无法在官网上评估 (#36)





 
我也遇到了同样的情况，学长可以帮助一下吗
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 201722111112027** [comment]
同学解决了吗？我也遇到一样的问题了。格式一模一样，就是出不了结果
