### ISSUE TITLE
关于数据预处理问题

### ISSUE THREAD

**Issue by rightchose** [HonglinChu/SiamTrackers#39]
[https://github.com/HonglinChu/SiamTrackers/blob/master/7-SiamRPNpp/SiamRPNpp-DW/siamrpnpp/datasets/dataset.py](https://github.com/HonglinChu/SiamTrackers/blob/master/7-SiamRPNpp/SiamRPNpp-DW/siamrpnpp/datasets/dataset.py)
作者你好，这里的dataset文件似乎没有对输入的图片做从0-255到0-1的映射，按理说一般网络不应该会对输入的图像数据统一到0-1之间吗？

**Comment by HonglinChu** [comment]
很久没关注数据加载部分的代码了，正常是要归一化到0-1之间。最简单的验证方法是你用vscode单步debug，查看一下输入网络的图片数值大小
