### ISSUE TITLE
wechat QR code out of date

### ISSUE THREAD

**Issue by lycqu** [HonglinChu/SiamTrackers#4]
wechat QR code out of date，I  want to join you !

**Comment by HonglinChu** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lycqu"<notifications@github.com&gt;; 
发送时间: 2020年6月18日(星期四) 下午3:21
收件人: "HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [HonglinChu/SiamTrackers] wechat QR code out of date (#4)





 
wechat QR code out of date，I  want to join you !

**Comment by HonglinChu** [comment]
> wechat QR code out of date，I want to join you !
I am sorry, i have been busy recently. Just now, i  updated the wechat QR code!

**Comment by HonglinChu** [comment]
I am sorry, i have been busy recently. Just now, i updated the wechat QR code!
