### ISSUE TITLE
siamRPN  请问解压YTB&VID需要多大内存啊，我480g的硬盘不够正常吗？

### ISSUE THREAD

**Issue by yanye-hub** [HonglinChu/SiamTrackers#40]

**Comment by HonglinChu** [comment]
siamrpn直接用四个训练集，参考学习siamrpnpp-up或者siamrpnpp-dw的代码

**Comment by HonglinChu** [comment]
YTB&VID 数据集挺大地，解压之后好像100G吧，480G硬盘肯定应该够了，检查一下你的硬盘数据对齐的格式，硬盘数据对齐格式太大会导出实际占用空间比文件大小大很多。或者重新格式化硬盘为4K对齐

**Comment by yanye-hub** [comment]
> YTB&VID 数据集挺大地，解压之后好像100G吧，480G硬盘肯定应该够了，检查一下你的硬盘数据对齐的格式，硬盘数据对齐格式太大会导出实际占用空间比文件大小大很多。或者重新格式化硬盘为4K对齐
太感谢了！

**Comment by yanye-hub** [comment]
太感谢了
