### ISSUE TITLE
Can you provide pretrained models for these trackers

### ISSUE THREAD

**Issue by chetanpandey1266** [HonglinChu/SiamTrackers#43]
I am unable to train these trackers due to hardware constraints. Can someone please provide pre-trained weights. I specifically need for SiamFC++.

**Comment by HonglinChu** [comment]
I have provide download link，you can find it in 

https://github.com/HonglinChu/SiamTrackers/tree/master/9-SiamFCpp/SiamFCpp-GOT

**Comment by chetanpandey1266** [comment]
Thanks @HonglinChu
