### ISSUE TITLE
Dataloader加载数据太慢

### ISSUE THREAD

**Issue by qfwysw** [HonglinChu/SiamTrackers#45]
感谢您的贡献！
我在使用过程中出现了一些问题。
我使用的是siamrpn，我在训练的时候出现了数据加载太慢的情况，我已经将batchsize改为1了，迟迟无法获得数据。
![image](https://user-images.githubusercontent.com/53482524/122628211-768e6b80-d0e7-11eb-9446-17a7d7e67f93.png)
我在dataset下调用还是挺快的，train_dataset.__getitem__(1)， 但是不知道为什么在Dataloader中无法输出数据。

**Comment by HonglinChu** [comment]
1、数据加载慢的问题之前没遇到过，可以尝试先运行my_train.py 单步调试，定位到数据加载部分看看是什么情况。
2、学习siamrpn的话建议你直接看siamrpnpp-up代码，这个可以复现和siamrpn原文比较接近的精度


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HonglinChu/SiamTrackers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月19日(星期六) 上午10:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[HonglinChu/SiamTrackers] Dataloader加载数据太慢 (#45)





 
感谢您的贡献！
 我在使用过程中出现了一些问题。
 我使用的是siamrpn，我在训练的时候出现了数据加载太慢的情况，我已经将batchsize改为1了，迟迟无法获得数据。
 
 我在dataset下调用还是挺快的，train_dataset.getitem(1)， 但是不知道为什么在Dataloader中无法输出数据。
