### ISSUE TITLE
Baidu ISSUE

### ISSUE THREAD

**Issue by amirhamidihd** [HonglinChu/SiamTrackers#46]
All the models are uploaded at the Baidu, Baidu is not accessible for us,

Can you upload the models and everything is necessary for running the codes on the Google Drive?

**Comment by HonglinChu** [comment]
I am  sorry, my Google Drive only has 15GB of storage space, which is not enough to store so many models and training data sets.

**Comment by amirhamidihd** [comment]
Thanks for your reply,

I only need one of the models for testing your code. we can download training datasets from other sources,

**Comment by HonglinChu** [comment]
Which model do you want to download, all models?

**Comment by amirhamidihd** [comment]
This is a good repository for Siam based tracker, and Its a good idea to have all models, but if you have a restriction to upload all models, it would be good for me to run SIAMCAR, SIAMFCpp and LightTrack.

if you accepted I could send my google account to you and upload them all. It is clear that , I will never use this account again.

**Comment by HonglinChu** [comment]
I'm very sorry that i haven't done tracking for a long time, and i suggest you to use the code we provide to retrain them only with the got10k data set, which won't take long.
