### ISSUE TITLE
ImportError: cannot import name 'region' from partially initialized module 'toolkit.utils' (most likely due to a circular import) 

### ISSUE THREAD

**Issue by izhimahu** [HonglinChu/SiamTrackers#47]
![image](https://user-images.githubusercontent.com/66286551/130929476-63de4956-e58c-4cbb-bcfb-e4b9544e3f96.png)
请问有人能帮忙解决一下这个问题吗

**Comment by EavanLi** [comment]
我也是。（在对updatenet进行my_test.py时出现的该问题）
我的解决办法是:
先cd ./toolkit/utils/
然后执行python setup.py build_ext --inplace这一步。
但是我看toolkit/utils/中没有setup.py文件，我是将pysot中的setup.py拷贝过来然后执行的python setup.py build_ext --inplace。

**Comment by HonglinChu** [comment]
https://github.com/STVIR/pysot ，如果有region的报错，是因为没有成功编译setup.py，具体可以参考pysot的的 Getting Help部分

**Comment by Whyrailgun** [comment]
![image](https://user-images.githubusercontent.com/105217559/225843108-eab1f5bf-6b14-4a92-91d4-71f32d7aa0fd.png)
请问我在编译setup.py后依然会有region的报错是为什么啊
