### ISSUE TITLE
vot评估画图问题

### ISSUE THREAD

**Issue by xiaoxianya** [HonglinChu/SiamTrackers#48]
up主你好，pysot带的vot只能评测出eao的数据，不能画vot的评估图，对于vot评估图请问你有好的解决方法吗？

**Comment by izhimahu** [comment]
请问你有运行updatenet吗？我不太懂那个toolkit是要怎么用呢。刚运行mytest就报错。ImportError: cannot import name 'region' from partially initialized module 'toolkit.utils' (most likely due to a circular import)。你有遇到吗

**Comment by xiaoxianya** [comment]
> 请问你有运行updatenet吗？我不太懂那个toolkit是要怎么用呢。刚运行mytest就报错。ImportError: cannot import name 'region' from partially initialized module 'toolkit.utils' (most likely due to a circular import)。你有遇到吗

这个我倒没有遇到，我是看的up的视频跑起来的
