### ISSUE TITLE
微信群提示只能邀请才能进去了

### ISSUE THREAD

**Issue by forscherzhang** [HonglinChu/SiamTrackers#5]

**Comment by HonglinChu** [comment]
Sorry, wechat group has more than 100 people！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "forscherzhang"<notifications@github.com&gt;; 
发送时间: 2020年7月1日(星期三) 晚上8:00
收件人: "HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [HonglinChu/SiamTrackers] 微信群提示只能邀请才能进去了 (#5)
