### ISSUE TITLE
SiamRPNpp训练过程中出现“已杀死”后训练结束的问题

### ISSUE THREAD

**Issue by Hxxxzz** [HonglinChu/SiamTrackers#54]
您好，我在训练alexnet的SiamRPNpp时，加载模型和数据集正常，但训练两次都出现“已杀死”的打印信息后就结束了训练，一次到99%，一次到80%，请问是什么问题

**Comment by HonglinChu** [comment]
SiamRPNpp训练过程中, 内存占用可能会越来越大,内存最好>=64G,关于内存使用情况你可以定时查看一下; 另外一种可能就是GPU显寸突然不够了,可能在训练到99%或者80%的时刻, 你又同时运行了其他的需要占用显存的程序,导致程序崩掉

**Comment by Hxxxzz** [comment]
非常感谢！
