### ISSUE TITLE
SiamCAR训练报错

### ISSUE THREAD

**Issue by job333** [HonglinChu/SiamTrackers#55]
有人知道这个错该怎么改吗
Traceback (most recent call last):
  File "train.py", line 313, in <module>
    main()
  File "train.py", line 309, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "train.py", line 204, in train
    outputs = model(data)
  File "D:\Ana\envs\polyyolo\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Ana\envs\polyyolo\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "D:\Ana\envs\polyyolo\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\siamese-rpn-pytorch\za\SiamTrackers-master\SiamCAR\SiamCAR\siamcar\models\model_builder.py", line 95, in forward
    if data.size(1)!=3 and data.size(0)!=1:
AttributeError: 'dict' object has no attribute 'size'

**Comment by cuikf** [comment]
我也是这个问题 请问您解决了吗？

**Comment by HonglinChu** [comment]
> 有人知道这个错该怎么改吗 Traceback (most recent call last): File "train.py", line 313, in main() File "train.py", line 309, in main train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer) File "train.py", line 204, in train outputs = model(data) File "D:\Ana\envs\polyyolo\lib\site-packages\torch\nn\modules\module.py", line 547, in **call** result = self.forward(*input, **kwargs) File "D:\Ana\envs\polyyolo\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward return self.module(*inputs[0], **kwargs[0]) File "D:\Ana\envs\polyyolo\lib\site-packages\torch\nn\modules\module.py", line 547, in **call** result = self.forward(*input, **kwargs) File "E:\siamese-rpn-pytorch\za\SiamTrackers-master\SiamCAR\SiamCAR\siamcar\models\model_builder.py", line 95, in forward if data.size(1)!=3 and data.size(0)!=1: AttributeError: 'dict' object has no attribute 'size'



> 有人知道这个错该怎么改吗 Traceback (most recent call last): File "train.py", line 313, in main() File "train.py", line 309, in main train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer) File "train.py", line 204, in train outputs = model(data) File "D:\Ana\envs\polyyolo\lib\site-packages\torch\nn\modules\module.py", line 547, in **call** result = self.forward(*input, **kwargs) File "D:\Ana\envs\polyyolo\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward return self.module(*inputs[0], **kwargs[0]) File "D:\Ana\envs\polyyolo\lib\site-packages\torch\nn\modules\module.py", line 547, in **call** result = self.forward(*input, **kwargs) File "E:\siamese-rpn-pytorch\za\SiamTrackers-master\SiamCAR\SiamCAR\siamcar\models\model_builder.py", line 95, in forward if data.size(1)!=3 and data.size(0)!=1: AttributeError: 'dict' object has no attribute 'size'


(1) 遇到上述问题可以查看一下data是否包含 'template', 'search', 'label_cls', 'bbox' 这四项, 如果不包含说明你的数据加载有误;
如果你的data内容是正确的格式, 正常情况下,data是有size这个属性的. 
(2) 尝试去除 if和else的判断, forward改写成如下形式, 如果还有报错, 那就是传入的data有问题,应该考虑你的数据加载部分.

  # # # 正常训练的时候有使用如下forward 
    def forward(self, data):  
        """ only used in training
        """
            template = data['template'].cuda()
            search = data['search'].cuda()
            label_cls = data['label_cls'].cuda()
            label_loc = data['bbox'].cuda()
            # get feature
            zf = self.backbone(template) #[32, 3, 127, 127] --> [B,C,,H,W]
            xf = self.backbone(search)#[32, 3, 255, 255]
            if cfg.ADJUST.ADJUST:
                zf = self.neck(zf) # 通道压缩-->256 , 空间维度中心裁剪[15,15]-->[7,7]
                xf = self.neck(xf) # 通道压缩-->256, 空间维度[31,31](对应255的输入大小)
            # 三组特征分别进行相关操作 
            if cfg.BACKBONE.TYPE=='resnet50': # ResNet,三组特征卷积操作 
                features = self.xcorr_depthwise(xf[0],zf[0])
                for i in range(len(xf)-1):
                    features_new = self.xcorr_depthwise(xf[i+1],zf[i+1])
                    features = torch.cat([features,features_new],1)
                features = self.down(features) # 通道压缩 768 --> 256

            elif cfg.BACKBONE.TYPE=='alexnet': # AlexNet
                features = self.xcorr_depthwise(xf,zf) # [32, 256, 22, 22], [32, 256,6,6]

            cls, loc, cen = self.car_head(features) #[32, 256, 25, 25]--> cls[B,2,25,25], loc[B,4,25,25], cen[B,1,25,25]
            locations = compute_locations(cls, cfg.TRACK.STRIDE) # 这一步涉及特征图到原图的映射，非常重要。STRIDE=8
            cls = self.log_softmax(cls) #[32,2,25,25] --> [32,1,25,25,2]
            cls_loss, loc_loss, cen_loss = self.loss_evaluator(
                locations,
                cls,
                loc,
                cen, label_cls, label_loc
            )
            # get loss
            outputs = {}
            outputs['total_loss'] = cfg.TRAIN.CLS_WEIGHT * cls_loss + \
                cfg.TRAIN.LOC_WEIGHT * loc_loss + cfg.TRAIN.CEN_WEIGHT * cen_loss
            outputs['cls_loss'] = cls_loss
            outputs['loc_loss'] = loc_loss
            outputs['cen_loss'] = cen_loss
            return outputs

**Comment by cuikf** [comment]
> > 有人知道这个错该怎么改吗 Traceback (most recent call last): File "train.py", line 313, in main() File "train.py", line 309, in main train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer) File "train.py", line 204, in train outputs = model(data) File "D:\Ana\envs\polyyolo\lib\site-packages\torch\nn\modules\module.py", line 547, in **call** result = self.forward(*input, **kwargs) File "D:\Ana\envs\polyyolo\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward return self.module(*inputs[0], **kwargs[0]) File "D:\Ana\envs\polyyolo\lib\site-packages\torch\nn\modules\module.py", line 547, in **call** result = self.forward(*input, **kwargs) File "E:\siamese-rpn-pytorch\za\SiamTrackers-master\SiamCAR\SiamCAR\siamcar\models\model_builder.py", line 95, in forward if data.size(1)!=3 and data.size(0)!=1: AttributeError: 'dict' object has no attribute 'size'
> 
> > 有人知道这个错该怎么改吗 Traceback (most recent call last): File "train.py", line 313, in main() File "train.py", line 309, in main train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer) File "train.py", line 204, in train outputs = model(data) File "D:\Ana\envs\polyyolo\lib\site-packages\torch\nn\modules\module.py", line 547, in **call** result = self.forward(*input, **kwargs) File "D:\Ana\envs\polyyolo\lib\site-packages\torch\nn\parallel\data_parallel.py", line 150, in forward return self.module(*inputs[0], **kwargs[0]) File "D:\Ana\envs\polyyolo\lib\site-packages\torch\nn\modules\module.py", line 547, in **call** result = self.forward(*input, **kwargs) File "E:\siamese-rpn-pytorch\za\SiamTrackers-master\SiamCAR\SiamCAR\siamcar\models\model_builder.py", line 95, in forward if data.size(1)!=3 and data.size(0)!=1: AttributeError: 'dict' object has no attribute 'size'
> 
> (1) 遇到上述问题可以查看一下data是否包含 'template', 'search', 'label_cls', 'bbox' 这四项, 如果不包含说明你的数据加载有误; 如果你的data内容是正确的格式, 正常情况下,data是有size这个属性的. (2) 尝试去除 if和else的判断, forward改写成如下形式, 如果还有报错, 那就是传入的data有问题,应该考虑你的数据加载部分.
> 
> # # # 正常训练的时候有使用如下forward
> ```
> def forward(self, data):  
>     """ only used in training
>     """
>         template = data['template'].cuda()
>         search = data['search'].cuda()
>         label_cls = data['label_cls'].cuda()
>         label_loc = data['bbox'].cuda()
>         # get feature
>         zf = self.backbone(template) #[32, 3, 127, 127] --> [B,C,,H,W]
>         xf = self.backbone(search)#[32, 3, 255, 255]
>         if cfg.ADJUST.ADJUST:
>             zf = self.neck(zf) # 通道压缩-->256 , 空间维度中心裁剪[15,15]-->[7,7]
>             xf = self.neck(xf) # 通道压缩-->256, 空间维度[31,31](对应255的输入大小)
>         # 三组特征分别进行相关操作 
>         if cfg.BACKBONE.TYPE=='resnet50': # ResNet,三组特征卷积操作 
>             features = self.xcorr_depthwise(xf[0],zf[0])
>             for i in range(len(xf)-1):
>                 features_new = self.xcorr_depthwise(xf[i+1],zf[i+1])
>                 features = torch.cat([features,features_new],1)
>             features = self.down(features) # 通道压缩 768 --> 256
> 
>         elif cfg.BACKBONE.TYPE=='alexnet': # AlexNet
>             features = self.xcorr_depthwise(xf,zf) # [32, 256, 22, 22], [32, 256,6,6]
> 
>         cls, loc, cen = self.car_head(features) #[32, 256, 25, 25]--> cls[B,2,25,25], loc[B,4,25,25], cen[B,1,25,25]
>         locations = compute_locations(cls, cfg.TRACK.STRIDE) # 这一步涉及特征图到原图的映射，非常重要。STRIDE=8
>         cls = self.log_softmax(cls) #[32,2,25,25] --> [32,1,25,25,2]
>         cls_loss, loc_loss, cen_loss = self.loss_evaluator(
>             locations,
>             cls,
>             loc,
>             cen, label_cls, label_loc
>         )data是否包含 'template', 'search', 'label_cls', 'bbox' 这四项
>         # get loss
>         outputs = {}
>         outputs['total_loss'] = cfg.TRAIN.CLS_WEIGHT * cls_loss + \
>             cfg.TRAIN.LOC_WEIGHT * loc_loss + cfg.TRAIN.CEN_WEIGHT * cen_loss
>         outputs['cls_loss'] = cls_loss
>         outputs['loc_loss'] = loc_loss
>         outputs['cen_loss'] = cen_loss
>         return outputs
> ```

您好，感谢您的回答。我的data里包含 'template', 'search', 'label_cls', 'bbox' 这四项，但是依旧会报size的错；去掉if else判断以后改成以下代码就能够成功运行：
    def forward(self, data):   # data: template[B,C,TEMP_SIZE,TEMP_SIZE], search[B,C,SEARCH_SIZE,SEARCH_SIZE], label_cls[B,OUTPUT_SIZE,OUTPUT_SIZE], bbox[B,4]
        """ only used in training
        """
        template = data['template'].cuda()
        search = data['search'].cuda()
        label_cls = data['label_cls'].cuda()
        label_loc = data['bbox'].cuda()

        # get feature
        zf = self.backbone(template) #[32, 3, 127, 127] --> [B,C,,H,W]
        xf = self.backbone(search)#[32, 3, 255, 255]
        if cfg.ADJUST.ADJUST:
            zf = self.neck(zf) # 通道压缩-->256 , 空间维度中心裁剪[15,15]-->[7,7]
            xf = self.neck(xf) # 通道压缩-->256, 空间维度[31,31](对应255的输入大小)

        # # 三组特征分别进行相关操作
        # if cfg.BACKBONE.TYPE=='resnet50': # ResNet,三组特征卷积操作
        #     features = self.xcorr_depthwise(xf[0],zf[0])
        #     for i in range(len(xf)-1):
        #         features_new = self.xcorr_depthwise(xf[i+1],zf[i+1])
        #         features = torch.cat([features,features_new],1)
        #     features = self.down(features) # 通道压缩 768 --> 256
        #
        # elif cfg.BACKBONE.TYPE=='alexnet': # AlexNet
        #     features = self.xcorr_depthwise(xf,zf) # [32, 256, 22, 22], [32, 256,6,6]

        cls, loc, cen = self.car_head(zf,xf) #[32, 256, 25, 25]--> cls[B,2,25,25], loc[B,4,25,25], cen[B,1,25,25]
        locations = compute_locations(cls, cfg.TRACK.STRIDE) # 这一步涉及特征图到原图的映射，非常重要。STRIDE=8
        cls = self.log_softmax(cls) #[32,2,25,25] --> [32,1,25,25,2]
        cls_loss, loc_loss, cen_loss = self.loss_evaluator(
            locations,
            cls,
            loc,
            cen, label_cls, label_loc
        )

        # get loss
        outputs = {}
        outputs['total_loss'] = cfg.TRAIN.CLS_WEIGHT * cls_loss + \
            cfg.TRAIN.LOC_WEIGHT * loc_loss + cfg.TRAIN.CEN_WEIGHT * cen_loss
        outputs['cls_loss'] = cls_loss
        outputs['loc_loss'] = loc_loss
        outputs['cen_loss'] = cen_loss
        return outputs
