### ISSUE TITLE
siamFC 的my_test ,my_eval

### ISSUE THREAD

**Issue by Quan-w** [HonglinChu/SiamTrackers#56]
我运行my_eval的时候如果那个e.run是注释掉的话他会报错说找不到GOT-10K_Val_0000001，去掉注释能正常运行，我看学长你B站的演示视频里面也是注释掉的但是可以正常运行不知道为什么。
运行my_test的时候会报错在训完180个后
--Sequence 180/180: GOT-10k_Test_000180
 Repetition: 1
  Found results, skipping GOT-10k_Test_000180
Records saved at ../SiamFC.zip
Login and follow instructions on
http://got-10k.aitestunion.com/submit_instructions
to upload and evaluate your tracking results

Traceback (most recent call last):
  File "F:/SiamTrackers-master/SiamFC/SiamFC/bin/my_test.py", line 74, in <module>
    prec_score, succ_score, succ_rate = e.report([tracker.name])
TypeError: cannot unpack non-iterable NoneType object

**Comment by HonglinChu** [comment]
你可以在 这行代码打断点, prec_score, succ_score, succ_rate = e.report([tracker.name]),  调试一下, 代码运行到这行的时候, 跳到 e.report函数里面,看看具体是在内部哪一行代码出错, 查看相关的变量是什么
