### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by izhimahu** [HonglinChu/SiamTrackers#57]
![image](https://user-images.githubusercontent.com/66286551/154450536-6aac3606-c4dd-4f80-981c-64c67c3300e2.png)请问SiamTrackers]/UpdateNet-DaSiamRPN/中models提供的vot2016和vot2018模型和您在readme中提供的模型有什么区别吗
![image](https://user-images.githubusercontent.com/66286551/154450866-41f04157-10d5-46c3-a19c-7353bf843797.png)

**Comment by HonglinChu** [comment]
> ![image](https://user-images.githubusercontent.com/66286551/154450536-6aac3606-c4dd-4f80-981c-64c67c3300e2.png)请问SiamTrackers]/UpdateNet-DaSiamRPN/中models提供的vot2016和vot2018模型和您在readme中提供的模型有什么区别吗 ![image](https://user-images.githubusercontent.com/66286551/154450866-41f04157-10d5-46c3-a19c-7353bf843797.png)

你好vot2016.pth.tar和vot2018.pth.tar是原作者提供的UpdateNet模型更新网络部分的权重. SiamRPNBIG.model是DaSiamRPN作者提供的DaSiamRPN目标跟踪部分的网络权重.

**Comment by izhimahu** [comment]
> > ![image](https://user-images.githubusercontent.com/66286551/154450536-6aac3606-c4dd-4f80-981c-64c67c3300e2.png)请问SiamTrackers]/UpdateNet-DaSiamRPN/中models提供的vot2016和vot2018模型和您在readme中提供的模型有什么区别吗 ![image](https://user-images.githubusercontent.com/66286551/154450866-41f04157-10d5-46c3-a19c-7353bf843797.png)
> 
> 你好vot2016.pth.tar和vot2018.pth.tar是原作者提供的UpdateNet模型更新网络部分的权重. SiamRPNBIG.model是DaSiamRPN作者提供的DaSiamRPN目标跟踪部分的网络权重.

谢谢回复
