### ISSUE TITLE
为什么提示这个包找不到了？需要配置什么环境吗。

### ISSUE THREAD

**Issue by zk-282263802** [HonglinChu/SiamTrackers#60]
为什么提示这个包找不到了？需要配置什么环境吗。
![微信截图_20220315221244](https://user-images.githubusercontent.com/55752197/158396822-8838624b-53d5-4a81-996f-ad2c76d31619.png)

**Comment by HonglinChu** [comment]
siamfc的代码有更改,这是新的地址 https://github.com/HonglinChu/SiamTrackers/tree/master/SiamFC/SiamFC

**Comment by HonglinChu** [comment]
> 为什么提示这个包找不到了？需要配置什么环境吗。 ![微信截图_20220315221244](https://user-images.githubusercontent.com/55752197/158396822-8838624b-53d5-4a81-996f-ad2c76d31619.png)
在命令行进入siamfc的项目根目录:  cd SiamTrackers/SiamFC/SiamFC
在siamfc项目的根目录输入命令:  python ./bin/my_eval.py 

my_eval.py 文件开头设置了默认路径是项目根目录, siamfc文件夹就是项目根目录里
`
import os
import sys
sys.path.append(os.getcwd())
`

**Comment by zk-282263802** [comment]
您好，这个问题根据您的提示，我已经解决了，但是又出现了另一个新的问题。
result 原来就是空的吗？他提示在 result 目录下没有 .txt 文件？还有 OTB-2015 数据集我应该是用您提供的，还是官网下载的？我看您百度云中还有一个修改版的。。。
![微信截图_20220316183834](https://user-images.githubusercontent.com/55752197/158572115-d45cc045-44f7-438c-a246-029880b73ebd.png)

**Comment by zk-282263802** [comment]
您好，非常感谢。根据您的提示，我这边问题已经处理好的。谢谢！！！
