### ISSUE TITLE
关于 SiamRpn 训练的问题。

### ISSUE THREAD

**Issue by zk-282263802** [HonglinChu/SiamTrackers#62]
您好，我在使用 SiamRPN 包中的 my_train 进行训练是，报出一个错误。

![微信截图_20220319172354](https://user-images.githubusercontent.com/55752197/159115724-7bec9b78-5992-45d7-9bc5-557f9bb01994.png)

其中预训练模型我是从别的别的包找到的（文件如下图）。是不是这个原因？

![微信截图_20220319173010](https://user-images.githubusercontent.com/55752197/159115748-6eda983d-1c04-45aa-ab86-51eac89b932a.png)

**Comment by HonglinChu** [comment]
运行my_train的时候只需要加在alexnet网络权重就可以了. checkpoint_e41-16-up.pth 是已经训练好的模型, 当然也可以加在它来初始化网络进行重新训练.  报错信息很明确了,加载的state_dict里面没有关键字 epoch, state_dict和optimizer. 具体解决办法就是在加载 checkpoint_e41-16-up.pth 模型的时候取出关键字state_dict的内容.

**Comment by zk-282263802** [comment]
您好，我找到原因了，应该是我找的预训练模型网络框架和RPN的网络框架不一致造成的。

现在还有一个问题，我在看 **下图归一化操作中**。
![微信截图_20220320182830](https://user-images.githubusercontent.com/55752197/159158272-07eda903-79be-4d11-be93-edc400a9f09a.png)
在训练中无法保证对数的 **真数始终大于0**。我应该将其加上绝对值吗？
![微信截图_20220320183435](https://user-images.githubusercontent.com/55752197/159158342-9a6aad98-ac82-4691-ab7f-3c7582429aa7.png)

![微信截图_20220320183545](https://user-images.githubusercontent.com/55752197/159158361-35f48fad-0743-43f1-ad7e-6fb3ea6977a2.png)

**Comment by wangjie0615** [comment]
> 您好，我找到原因了，应该是我找的预训练模型网络框架和RPN的网络框架不一致造成的。
> 
> 现在还有一个问题，我在看 **下图归一化操作中**。 ![微信截图_20220320182830](https://user-images.githubusercontent.com/55752197/159158272-07eda903-79be-4d11-be93-edc400a9f09a.png) 在训练中无法保证对数的 **真数始终大于0**。我应该将其加上绝对值吗？ ![微信截图_20220320183435](https://user-images.githubusercontent.com/55752197/159158342-9a6aad98-ac82-4691-ab7f-3c7582429aa7.png)
> 
> ![微信截图_20220320183545](https://user-images.githubusercontent.com/55752197/159158361-35f48fad-0743-43f1-ad7e-6fb3ea6977a2.png)

您好，请问您后来解决这个问题了吗？如何解决的？

**Comment by OceanCanoe** [comment]
> 您好，我找到原因了，应该是我找的预训练模型网络框架和RPN的网络框架不一致造成的。
> 
> 现在还有一个问题，我在看 **下图归一化操作中**。 ![微信截图_20220320182830](https://user-images.githubusercontent.com/55752197/159158272-07eda903-79be-4d11-be93-edc400a9f09a.png) 在训练中无法保证对数的 **真数始终大于0**。我应该将其加上绝对值吗？ ![微信截图_20220320183435](https://user-images.githubusercontent.com/55752197/159158342-9a6aad98-ac82-4691-ab7f-3c7582429aa7.png)
> 
> ![微信截图_20220320183545](https://user-images.githubusercontent.com/55752197/159158361-35f48fad-0743-43f1-ad7e-6fb3ea6977a2.png)

你好，请问你有能用的alexnet.pth文件吗，作者说的checkpoint_e41-16-up.pth我也没找到。

**Comment by HonglinChu** [comment]
这里是alexnet的模型，链接: https://pan.baidu.com/s/1ljNZe03ig-TChxBTQDmv4Q 提取码: jkpw 复制这段内容后打开百度网盘手机App，操作更方便哦


另外，SiamRPN是好几年前的论文，建议你直接尝试Anchor free系列的跟踪方法




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月14日(星期六) 下午5:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HonglinChu/SiamTrackers] 关于 SiamRpn 训练的问题。 (Issue #62)





  
您好，我找到原因了，应该是我找的预训练模型网络框架和RPN的网络框架不一致造成的。
 
现在还有一个问题，我在看 下图归一化操作中。  在训练中无法保证对数的 真数始终大于0。我应该将其加上绝对值吗？ 
 

  
你好，请问你有能用的alexnet.pth文件吗，作者说的checkpoint_e41-16-up.pth我也没找到。

**Comment by OceanCanoe** [comment]
感谢honglin大佬，我现在毕业论文确实准备做anchor-free的目标跟踪方法，想先从SiamRPN入手，大佬的github帮助了我很多，后续我想自己着手复现和改进，再次感谢🙏



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月18日(周三) 晚上7:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HonglinChu/SiamTrackers] 关于 SiamRpn 训练的问题。 (Issue #62)




 这里是alexnet的模型，链接: https://pan.baidu.com/s/1ljNZe03ig-TChxBTQDmv4Q 提取码: jkpw 复制这段内容后打开百度网盘手机App，操作更方便哦 
 
 
 另外，SiamRPN是好几年前的论文，建议你直接尝试Anchor free系列的跟踪方法 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2023年1月14日(星期六) 下午5:04 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [HonglinChu/SiamTrackers] 关于 SiamRpn 训练的问题。 (Issue #62) 
 
 
 
 
 
    
 您好，我找到原因了，应该是我找的预训练模型网络框架和RPN的网络框架不一致造成的。 
   
 现在还有一个问题，我在看 下图归一化操作中。  在训练中无法保证对数的 真数始终大于0。我应该将其加上绝对值吗？  
   
 
    
 你好，请问你有能用的alexnet.pth文件吗，作者说的checkpoint_e41-16-up.pth我也没找到。

**Comment by HonglinChu** [comment]
可是尝试一下这个小网络，也是anchor free的，训练推理都很快，比SiamRPN效果要好https://github.com/HonglinChu/SiamTrackers/tree/master/NanoTrack

**Comment by OceanCanoe** [comment]
感谢大佬，我之前有关注过这个，苦于没有代码，我这两天研究一下🤔



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月20日(周五) 下午3:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [HonglinChu/SiamTrackers] 关于 SiamRpn 训练的问题。 (Issue #62)




 
可是尝试一下这个小网络，也是anchor free的，训练推理都很快，比SiamRPN效果要好https://github.com/HonglinChu/SiamTrackers/tree/master/NanoTrack

**Comment by OceanCanoe** [comment]
沧木
***@***.***



&nbsp;林哥你好，我下载了GOT-10k的数据集，但是第二步crop的百度网盘链接已经挂掉了



之前我找到过crop后的got-10k数据集，但是这个数据集解压后是60多G的.tar压缩包，单个大文件解压不了。






所以我之后要怎么获取这部分的数据集呢？
