### ISSUE TITLE
siamcar model_builder forwar()运行报错

### ISSUE THREAD

**Issue by Quan-w** [HonglinChu/SiamTrackers#64]
学长data是字典，您在forwad里对data.size(1)判断然后就报错了，dict没有data属性
def forward(self, data):
              # if data.size(1)!=3 and data.size(0)!=1:
               template = data['template'].cuda()
              search = data['search'].cuda()
              label_cls = data['label_cls'].cuda()
              label_loc = data['bbox'].cuda()
将if和下面的else注释掉可正常运行

**Comment by HonglinChu** [comment]
> 学长data是字典，您在forwad里对data.size(1)判断然后就报错了，dict没有data属性 def forward(self, data): # if data.size(1)!=3 and data.size(0)!=1: template = data['template'].cuda() search = data['search'].cuda() label_cls = data['label_cls'].cuda() label_loc = data['bbox'].cuda() 将if和下面的else注释掉可正常运行

感谢反馈, 你的解决方法是对的. 另外, else里面的内容是为了测试推理时间才加的, 训练的时候没有起作用.
