### ISSUE TITLE
使用您提供的nanotrack epoch_26 无法复现 EAO=30.6的结果

### ISSUE THREAD

**Issue by BlueBlueFF** [HonglinChu/SiamTrackers#65]

**Comment by HonglinChu** [comment]
你的测试结果是多少?

**Comment by baky198311** [comment]
> 你的测试结果是多少?

兄弟，我也遇到同样的问题，结果如下：
checkpoint_e26.pth VOT2018  lr-0.37  pk-_0.15  win-_0.455
------------------------------------------------------------
|Tracker Name| Accuracy | Robustness | Lost Number |  EAO  |
------------------------------------------------------------
| nanotrack  |  0.547   |   0.384    |    82.0     | 0.281 |
------------------------------------------------------------

checkpoint_e26.pth VOT2018  lr-0.38  pk-_0.15  win-_0.476
------------------------------------------------------------
|Tracker Name| Accuracy | Robustness | Lost Number |  EAO  |
------------------------------------------------------------
| nanotrack  |  0.542   |   0.370    |    79.0     | 0.277 |
