### ISSUE TITLE
NanoTrack 

### ISSUE THREAD

**Issue by abbasaqeel** [HonglinChu/SiamTrackers#66]
What is the paper of NanoTrack

**Comment by HonglinChu** [comment]
> What is the paper of NanoTrack

Sorry, nanotrack is just a project name of our own, and it is not a paper.

**Comment by baky198311** [comment]
> > What is the paper of NanoTrack
> 
> Sorry, nanotrack is just a project name of our own, and it is not a paper.

你好，我采用代码里面的默认参数进行训练，精度很低，请帮忙指点一下，谢谢！
python parse_got10k.py
python par_crop.py 271 16
python gen_json.py

![image](https://user-images.githubusercontent.com/34228642/169677513-8e5a77af-21bf-4334-b292-0fff5d6c8073.png)

**Comment by abbasaqeel** [comment]
Can I use it in my paper to publishing NanoTrack in ieee access

**Comment by ToBigboss** [comment]
> python par_crop.py 271 16

这个par_crop.py只是把exemplar和instanc裁切出来并保存，，最后训练的时候似乎没有用到crop的数据把？  我看了下parse_got10k.py会生成json文件，然后gen_json.py把got10k.json拆成train.json和val.json，，，有点不明白par_crop.py做这步干嘛
