### ISSUE TITLE
nanotrack 怎么转tensorrt?

### ISSUE THREAD

**Issue by JiangWeiHn** [HonglinChu/SiamTrackers#68]
非常感谢和欣赏你的工作，我想知道怎么把nanotrack的权重转换为tensorrt，我要在 nvidia的Xavier上部署这个模型。请指导一下，谢谢！

**Comment by HonglinChu** [comment]
> 非常感谢和欣赏你的工作，我想知道怎么把nanotrack的权重转换为tensorrt，我要在 nvidia的Xavier上部署这个模型。请指导一下，谢谢！

pytorch转tensorRT的例子很多, 可以参考https://blog.csdn.net/u012505617/article/details/110486468

**Comment by JiangWeiHn** [comment]
谢谢

**Comment by powerdoudou** [comment]
请问这个问题解决了吗
