### ISSUE TITLE
how can i convert dasiamrpn pytorch pretrained model to onnx ?

### ISSUE THREAD

**Issue by jcyhcs** [HonglinChu/SiamTrackers#69]
hi,professor:
like the topic said. please help!

**Comment by HonglinChu** [comment]
> hi,professor: like the topic said. please help!

Hi, you can refer to our new work and follow the steps, https://github.com/HonglinChu/SiamTrackers/blob/master/NanoTrack/pytorch2onnx.py 
And NanoTrack is better than dasiamrpn!

**Comment by jcyhcs** [comment]
thanks for your answer. one more question:
can offer a TensorRT deployment examples? python or c++ both ok,
please!

**Comment by HonglinChu** [comment]
> thanks for your answer. one more question: can offer a TensorRT deployment examples? python or c++ both ok, please!

No tensorRT version. This is our  C++ Version https://github.com/HonglinChu/NanoTrack
