### ISSUE TITLE
如何制作跟踪数据？

### ISSUE THREAD

**Issue by tianboguangding** [HonglinChu/SiamTrackers#7]
您好，感谢分享：）
想问一下，自己拍了自行车的几个小时的视频（假设用siamrpn++，只跟踪mobike类别），是不是先用labelimg之类的工具对该跟踪目标进行打标签，之后的步骤怎么处理呢？
多谢！

**Comment by HonglinChu** [comment]
使用 Labelimg  工具制作标签, 生成xml文件, 然后编写代码读取xml文件中目标的坐标位置, 然后按照OTB 中的gt格式保存到txt文件中
