### ISSUE TITLE
Hello, senior, about the drawing of the data set results

### ISSUE THREAD

**Issue by ZHISOT** [HonglinChu/SiamTrackers#70]
Could you please share VisDrone2019.json, DTB70.json and UAVDT.json. Thanks

**Comment by HonglinChu** [comment]
> Could you please share VisDrone2019.json, DTB70.json and UAVDT.json. Thanks
please refer to following link: https://github.com/HonglinChu/SiamTrackers/blob/master/SiamBAN/SiamBAN/toolkit/datasets/visdrone.py
`for  i in range(len(self.seq_names)):
            img_names = sorted(glob.glob(
            os.path.join(self.seq_dirs[i], '*.jpg')))
            img_names=[x.split('/VisDrone/')[-1] for x in img_names]
            gt_rect = np.loadtxt(self.anno_files[i], delimiter=',')
            data=dict()
            data['video_dir']=self.seq_names[i]
            data['init_rect']=gt_rect[0]
            data['img_names']=img_names
            data['gt_rect']=gt_rect
            data['attr']=0
            meta_data[self.seq_names[i]]=`
the  data in json format is generated online, no json file is required.

**Comment by HonglinChu** [comment]
> Could you please share VisDrone2019.json, DTB70.json and UAVDT.json. Thanks
> please refer to line 54-65 of following link: https://github.com/HonglinChu/SiamTrackers/blob/master/SiamBAN/SiamBAN/toolkit/datasets/visdrone.py
> The data in json format can generated online, no json file is required.

Could you please share VisDrone2019.json, DTB70.json and UAVDT.json. Thanks
please refer to line 54-65 of following link: https://github.com/HonglinChu/SiamTrackers/blob/master/SiamBAN/SiamBAN/toolkit/datasets/visdrone.py
The data in json format can generated online, no json file is required.

**Comment by HonglinChu** [comment]
> Could you please share VisDrone2019.json, DTB70.json and UAVDT.json. Thanks

please refer to line 54-65 of following link: https://github.com/HonglinChu/SiamTrackers/blob/master/SiamBAN/SiamBAN/toolkit/datasets/visdrone.py
The data in json format can generated online, no json file is required.

**Comment by ZHISOT** [comment]
Thank you very much for your prompt reply.
