### ISSUE TITLE
NanoTrack performance not good,why?

### ISSUE THREAD

**Issue by jcyhcs** [HonglinChu/SiamTrackers#72]
hi,professor:
i have success run NanoTrack on jetson tx2 with TensorRT accelerate! it very fast, fps almost 77fps~122fps!
but i test the dance_girl.mp4, i find the track not very good, always have lost and track error! 
the result is same with ncnn version.
i upload the result video of dance_girl, please tell me why NanoTrack is poor performance, and how to make it more better?

https://user-images.githubusercontent.com/34532224/168241641-38e4dbbf-90b0-455d-ae39-599c0a7e2b95.mp4

**Comment by powerdoudou** [comment]
hey bro, can you share how to run NanoTrack on jetson tx2 with TensorRT ??
