### ISSUE TITLE
NanoTrack在单卡3090使用默认参数训练时GPU利用率及缓存占用都很低

### ISSUE THREAD

**Issue by xkangKK** [HonglinChu/SiamTrackers#74]
你好，请问我使用单卡3090训练NanoTrack，GPU利用率很低，修改batchsize以后显存占用也没有明显提升。
请问这个是什么原因导致的呢？

**Comment by HonglinChu** [comment]
增大数据加载的线程数量尝试 4，8、12 or 16看看。另外，存放数据的磁盘最好是固态
