### ISSUE TITLE
您好，我在训练SiamRPN时显存利用低

### ISSUE THREAD

**Issue by jyCqupt** [HonglinChu/SiamTrackers#77]
数据集: GOT10k，cpu: AMD EPYC 7543 32-Core Processor GPU: RTX3090
cpu已经拉满了，但GPU利用率低，偶尔跳下20%，40%大部分时间为0
修改num_workers和batch_size参数无果
且每次train_loader处理完一次后都会卡顿一下

**Comment by HonglinChu** [comment]
训练的时候看一下每次读取数据的耗时,是不是卡在读取数据上了. CPU内存最好>64G, num_workers=4 or 8 or 12. 机械硬盘一般比较慢, 固态硬盘的还好. 另外, 可以尝试训练NanoTrack模型,效果可能比SiamRPN要好

**Comment by jyCqupt** [comment]
感谢大佬 应该是卡在读取数据了 我再研究一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月2日(星期六) 上午10:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HonglinChu/SiamTrackers] 您好，我在训练SiamRPN时显存利用低 (Issue #77)





 
训练的时候看一下每次读取数据的耗时,是不是卡在读取数据上了. CPU内存最好&gt;64G, num_workers=4 or 8 or 12. 机械硬盘一般比较慢, 固态硬盘的还好. 另外, 可以尝试训练NanoTrack模型,效果可能比SiamRPN要好
