### ISSUE TITLE
siamfc++  score 低

### ISSUE THREAD

**Issue by hito0512** [HonglinChu/SiamTrackers#78]
博主你好，有2个问题想咨询一下：
1）我用siamfc++训练数据之后，又在训练集上做了测试，将得分打印出来后，发现 score 值比较低一般在0.2到0.75这个区间，但是iou都是比较高的，AO值在0.85以上，我又在测试集上做了一下测试，发现score 更低，有些score直接在0.05以下，iou 较低，我想了一下，这个score只能叫相似度得分吧，它和分类识别的那个得分还是有点不一样的，但是这样低的得分，无法利用去做一些其他的判断，不知道博主有没有打印过这个得分，是不是也是这么低？
2）我将backbone改为了YOLOv5s的backbone，训练出来的模型经过检测，它的效果居然比alexnet更差，按理说YOLOv5中的PAN结构应该能够提取到更多的特征，跟踪更加平滑才对，现在反而效果更差了，不知道改动有什么需要注意的地方吗？

**Comment by HonglinChu** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HonglinChu/SiamTrackers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月12日(星期二) 下午4:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[HonglinChu/SiamTrackers] siamfc++  score 低 (Issue #78)

1) score和iou得分综合结果(一般是对应元素相乘)才是最终的得分, 代表属于目标的置信度.
2) 没尝试过YOLOv5的backbone, 之前尝试过ShuffleNetV2网络, 后面也用到了多尺度特征融合,训练效果也不太好. 你可以尝试仅使用8倍 or 16倍下次样特征(不进行PAN操作)进行相关操作.


 
博主你好，有2个问题想咨询一下：
 1）我用siamfc++训练数据之后，又在训练集上做了测试，将得分打印出来后，发现 score 值比较低一般在0.2到0.75这个区间，但是iou都是比较高的，AO值在0.85以上，我又在测试集上做了一下测试，发现score 更低，有些score直接在0.05以下，iou 较低，我想了一下，这个score只能叫相似度得分吧，它和分类识别的那个得分还是有点不一样的，但是这样低的得分，无法利用去做一些其他的判断，不知道博主有没有打印过这个得分，是不是也是这么低？
 2）我将backbone改为了YOLOv5s的backbone，训练出来的模型经过检测，它的效果居然比alexnet更差，按理说YOLOv5中的PAN结构应该能够提取到更多的特征，跟踪更加平滑才对，现在反而效果更差了，不知道改动有什么需要注意的地方吗？

**Comment by hito0512** [comment]
感谢回复，我调试了一下这个问题，score和iou得分综合结果(一般是对应元素相乘)才是最终的得分，这个我觉得是不对的，score和iou怎么能够相乘呢？得分低的原因我单步了一下是因为标签的问题，代码中标签制作有问题才回出现这个情况。
