### ISSUE TITLE
updatenet线性阶段训练问题

### ISSUE THREAD

**Issue by rkj12345** [HonglinChu/SiamTrackers#80]
请问updatenet模型复现您的代码，线性阶段生成模板后，进行训练生成的checkpoint，怎么测试哪个checkpoint最好，也就是您b站的1.2：加载1.1最好的模型这一步操作，运行test的话，如果step=2，我发现代码没有加载checkpoint啊，求大佬指教！

**Comment by HonglinChu** [comment]
> checkpoint

将updatenet和siamrpn结合, 直接在vot数据集上测试,根据eao指标选择最好的checkpoint(updatenet)模型

**Comment by rkj12345** [comment]
> 

我看您测试代码，只有step=3的时候才会加载checkpoint进行测试啊，那step=1,和step=2不需要加载嘛
