### ISSUE TITLE
SiamFCpp-pysot： 测试时候的GOT10k.json 怎么生成的

### ISSUE THREAD

**Issue by Ywenjun123** [HonglinChu/SiamTrackers#82]

**Comment by HonglinChu** [comment]
你应该通过运行setup.py文件根据自己的虚拟环境来生成region. 具体可以参考


https://github.com/STVIR/pysot/blob/master/setup.py


https://github.com/STVIR/pysot/blob/master/INSTALL.md


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HonglinChu/SiamTrackers"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月15日(星期一) 上午10:46
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[HonglinChu/SiamTrackers] SiamFCpp-pysot： ImportError: cannot import name 'region' from partially initialized module 'toolkit.utils' (Issue #82)





 
没找到生成region的文件啊
