### ISSUE TITLE
SiamTrackers/SiamRPN/SiamRPN/siamrpn/loss.py中rpn_cross_entropy_balance函数是否有误？

### ISSUE THREAD

**Issue by refreshment-coffee** [HonglinChu/SiamTrackers#83]
SiamTrackers/SiamRPN/SiamRPN/siamrpn/loss.py中rpn_cross_entropy_balance函数是否有误？
Line208行左右。
![image](https://user-images.githubusercontent.com/64402103/194683354-a85650ab-3825-4c6f-9581-05f369ae9759.png)
如上图所示，这个是计算正样本的交叉熵损失。
如下图所示，应该是类比计算负样本的交叉熵损失函数。
![image](https://user-images.githubusercontent.com/64402103/194683614-330beac9-1f92-49c5-9534-93f5b8d5e92a.png)

我发现，这两个的代码并不是很对应，是否有误呢？

关于负样本的交叉熵损失函数计算，我进行了如下修改：
![image](https://user-images.githubusercontent.com/64402103/194683688-faa3e37a-8cf3-43ae-b60b-97ffb85666a6.png)

**Comment by HonglinChu** [comment]
十分抱歉,时间有些久远细节记不起来了. 建议参考一下siamcar, siamban的方法,以及其他anchor free系列的跟踪方法是如何计算正负样本的.
