### ISSUE TITLE
NanoTrack test 太慢，请问您test也这么慢吗，test一次需要7min。而且我把SE和CA去掉，把h_swish换成silu后训练精度很低，请问一下有什么解决方法吗

### ISSUE THREAD

**Issue by maybeYe** [HonglinChu/SiamTrackers#84]
![QQ截图20221012174236](https://user-images.githubusercontent.com/71442036/195309711-1e669d60-a37a-457e-9254-f7e2a90a903a.png)

**Comment by HonglinChu** [comment]
你的EAO很低几乎为0,是因为算法训练效果太差了,导致运行很慢

**Comment by HonglinChu** [comment]
NanoTrack模型还是以前的模型,这次更新增加了对比实验, 其他算法的实验结果也已经放到results文件夹里,具体你可以对比一下https://github.com/HonglinChu/SiamTrackers/tree/master/NanoTrack



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月12日(星期三) 下午5:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [HonglinChu/SiamTrackers] NanoTrack test 太慢，请问您test也这么慢吗，test一次需要7min。而且我把SE和CA去掉，把h_swish换成silu后训练精度很低，请问一下有什么解决方法吗 (Issue #84)

**Comment by Coder-TieHH** [comment]
为什么我在运行test.py的时候走完了,60it之后，就会报错。调试的话发现ar_result数据都是nan
![image](https://github.com/HonglinChu/SiamTrackers/assets/130418678/c7f0601c-274a-4509-bf5a-5a546b55ab47)
![image](https://github.com/HonglinChu/SiamTrackers/assets/130418678/fe561557-06f7-442d-a19e-2273ca1c3c04)

**Comment by Coder-TieHH** [comment]
请各位大佬们不吝赐教，感谢！
