### ISSUE TITLE
DaSiamRPN Tracker疑问

### ISSUE THREAD

**Issue by Zeka-Fak** [HonglinChu/SiamTrackers#85]
大佬您好，看了DaSiamRPN中的代码，发现似乎并没有实现论文中提及的Distractor-aware Incremental Learning模块，请问是这样吗，如果没有的话请问大佬能提供吗，万分感谢。

**Comment by HonglinChu** [comment]
你好，我没有复现这部分的功能，论文也没有完全开源。建议你还是多看一下最近两年的跟踪方法，有很多都是完全开源的。
