### ISSUE TITLE
nanotrack 的跟踪框貌似并不是很稳定？

### ISSUE THREAD

**Issue by SyGoing** [HonglinChu/SiamTrackers#89]
我用大佬的NCNN工程nanotrack测试自己的一个视频，发现跟踪框不是很稳定，抖动比较厉害。同样测试了网上的一个ncnn版本的LightTrack感觉效果要好很多，请问如何提升精度，我看数据集貌似只用GOT，LightTrack使用了多个数据集混合训练，网络结构也有比较大差异

**Comment by ToBigboss** [comment]
> 你好， NanoTrackV1只是使用了GOT训练，效果和LightTrack相差确实比较大，前段时间提供了NanoTrackV2版本，使用了多个数据集训练。V2推理速度很快，精度相比V1有较大提升，目前只是在几个开源跟踪数据集上进行了对比https://github.com/HonglinChu/SiamTrackers/tree/master/NanoTrack#readme V2在输入和输出以及后处理逻辑方面和V1保持一致，不过V2模型并没有加入NCNN工程里面实测，你需要修改几个关键参数WINDOW_INFLUENCE: 0.490 PENALTY_K: 0.150 LR: 0.385

大佬，请教下  V2用了那几个数据集训练的啊？，我看config.py里面也就配了GOT的root和anno。 而且我还有个疑问就是config.py里面的__C.BAN.BAN配置为False，我的理解是应该为true把？  是不是这个config.py配置不是用来训练V2的？



__C.DATASET.NAMES = ('VID', 'YOUTUBEBB', 'DET', 'COCO', 'GOT', 'LASOT')

__C.DATASET.VID = CN() 
__C.DATASET.VID.ROOT = ''          # VID dataset path
__C.DATASET.VID.ANNO = ''
__C.DATASET.VID.FRAME_RANGE = 100
__C.DATASET.VID.NUM_USE =   100000 

__C.DATASET.YOUTUBEBB = CN()
__C.DATASET.YOUTUBEBB.ROOT = ''
__C.DATASET.YOUTUBEBB.ANNO = ''
__C.DATASET.YOUTUBEBB.FRAME_RANGE = 3
__C.DATASET.YOUTUBEBB.NUM_USE = 100000 

__C.DATASET.COCO = CN()
__C.DATASET.COCO.ROOT = ''
__C.DATASET.COCO.ANNO = ''
__C.DATASET.COCO.FRAME_RANGE = 1
__C.DATASET.COCO.NUM_USE =  100000  

__C.DATASET.DET = CN()
__C.DATASET.DET.ROOT = ''
__C.DATASET.DET.ANNO = ''
__C.DATASET.DET.FRAME_RANGE = 1
__C.DATASET.DET.NUM_USE = 100000 

__C.DATASET.GOT = CN()
__C.DATASET.GOT.ROOT = 'data/GOT-10k/crop511'
__C.DATASET.GOT.ANNO = 'data/GOT-10k/train.json'
__C.DATASET.GOT.FRAME_RANGE = 100
__C.DATASET.GOT.NUM_USE = 100000

__C.DATASET.LASOT = CN()
__C.DATASET.LASOT.ROOT = ''
__C.DATASET.LASOT.ANNO = ''
__C.DATASET.LASOT.FRAME_RANGE = 100
__C.DATASET.LASOT.NUM_USE = 100000 

__C.DATASET.VIDEOS_PER_EPOCH = 600000
