### ISSUE TITLE
siamrpn 测试VOT2018  请问你解决了这个BUG了么

### ISSUE THREAD

**Issue by chuanfuye** [HonglinChu/SiamTrackers#9]
root_dir = os.path.abspath('/media/xiaofei/ECD67E80D67E4B3A/test_data/vot
    2018') # VOT测试暂时遇到问题

**Comment by HonglinChu** [comment]
建议使用pycharm或者vscode 编辑器来进行单步调试，这样可以找到报错的地方，大部分的报错都可以通过单步调试解决的

**Comment by yangjiangeyjg** [comment]
> 
> 
> root_dir = os.path.abspath('/media/xiaofei/ECD67E80D67E4B3A/test_data/vot
> 2018') # VOT测试暂时遇到问题

老哥，请问你遇到的是什么问题啊，解决了吗
