### ISSUE TITLE
请问作者大佬知道SiamCAR 在OTB数据集上的参数设置吗

### ISSUE THREAD

**Issue by ivemcel** [HonglinChu/SiamTrackers#91]
使用您的SiamCAR 代码在OTB数据集上测试的presion只有0.63，论文中达到了0.9，相差很大，想请问下您知道或测试过SiamCAR在OTB数据集上的参数设置吗，感谢🙏

**Comment by dhy1222** [comment]
config文件中提供了超参数的设置
