### ISSUE TITLE
感觉nantrack的抖动还比较大，如果加深head的网络深度，加大epoch和batch会有大的提升吗？

### ISSUE THREAD

**Issue by pxEkin** [HonglinChu/SiamTrackers#93]

**Comment by HonglinChu** [comment]
V1的效果确实会差一些，V3的也马上要出来了，可以体验一下

**Comment by ToBigboss** [comment]
> V1的效果确实会差一些，V3的也马上要出来了，可以体验一下

好的 大佬，  很期待， 大概什么时候发布出来

**Comment by HonglinChu** [comment]
Now, you can try it!

**Comment by pxEkin** [comment]
> Now, you can try it!

大佬，我在原先v1的c++ demo上改了3处，跑v3模型，但是结果不对，应该是我遗漏了些东西，有空帮忙看看。 代码修改的地方：

**Comment by pxEkin** [comment]
> Now, you can try it!

大佬，我在原先v1的c++ demo上改了2处，跑v3模型，但是结果不对，应该是我遗漏了什么没修改？，有空帮忙看看。 代码修改的地方：
1. cfg的  WINDOW_INFLUENCE: 0.455  PENALTY_K: 0.138   LR: 0.348 
2. 直接将score_size设置为15 [因为head模型输出为15了]，total_stride任然为了16，这样去create_window和reate_grids

**Comment by HonglinChu** [comment]
V1和V2没有使用depthwise操作，V3在做相关操作的时候结合了depthwise 和pointwise两种方式（depthwise转换ncnn可能会不支持，之前尝试转换但是失败了，不清楚现在ncnn是否支持了）。模型转换过程可能没有明显报错，但在c++推理的时候网络输出值仍然异常，建议你debug查看一下转换之后的ncnn模型的输出数据。

**Comment by pxEkin** [comment]
> V1和V2没有使用depthwise操作，V3在做相关操作的时候结合了depthwise 和pointwise两种方式（depthwise转换ncnn可能会不支持，之前尝试转换但是失败了，不清楚现在ncnn是否支持了）。模型转换过程可能没有明显报错，但在c++推理的时候网络输出值仍然异常，建议你debug查看一下转换之后的ncnn模型的输出数据。

额 看了下，是模型转换出错了，，

**Comment by nihui** [comment]
pytorch转ncnn，推荐使用pnnx
https://github.com/pnnx/pnnx

**Comment by pxEkin** [comment]
@HonglinChu  我用MNN部署了，现在跑v2是ok的，但是跑v3结果就不对了。
我验证了pytorch和onnx以及MNN转换都是对的上的，结果如下：
pytorch模型结果跟onnx模型对比
![image](https://user-images.githubusercontent.com/40013733/222074440-d6ea5b70-857d-4fdd-bb69-b0e56329c323.png)
![image](https://user-images.githubusercontent.com/40013733/222075353-978d8931-c057-4d56-987c-22224499b6cb.png)

使用MNN的testMNNFromOnnx.py脚本测试
![image](https://user-images.githubusercontent.com/40013733/222075926-c0960e0e-5558-47ef-9d1d-9c6f77060c27.png)
![image](https://user-images.githubusercontent.com/40013733/222076050-572c61a5-d416-404f-ab07-db1197561234.png)

从上面数据对比可以看出：pytorch->onnx->MNN数据都是对上的

我看nano_tracker.py的代码除了改score_size，其他后处理基本上没动。。跑v3参数也改成了：WINDOW_INFLUENCE: 0.455 PENALTY_K: 0.138 LR: 0.348  score_size=15，其他前后处理都没变，结果是v2跟踪是对的，v3的跟踪很乱，结果明显不对。 

大佬， v3部署的时候，还有其他要注意的地方吗？

**Comment by y5300** [comment]
> @HonglinChu 我用MNN部署了，现在跑v2是ok的，但是跑v3结果就不对了。 我验证了pytorch和onnx以及MNN转换都是对的上的，结果如下： pytorch模型结果跟onnx模型对比 ![image](https://user-images.githubusercontent.com/40013733/222074440-d6ea5b70-857d-4fdd-bb69-b0e56329c323.png) ![image](https://user-images.githubusercontent.com/40013733/222075353-978d8931-c057-4d56-987c-22224499b6cb.png)
> 
> 使用MNN的testMNNFromOnnx.py脚本测试 ![image](https://user-images.githubusercontent.com/40013733/222075926-c0960e0e-5558-47ef-9d1d-9c6f77060c27.png) ![image](https://user-images.githubusercontent.com/40013733/222076050-572c61a5-d416-404f-ab07-db1197561234.png)
> 
> 从上面数据对比可以看出：pytorch->onnx->MNN数据都是对上的
> 
> 我看nano_tracker.py的代码除了改score_size，其他后处理基本上没动。。跑v3参数也改成了：WINDOW_INFLUENCE: 0.455 PENALTY_K: 0.138 LR: 0.348 score_size=15，其他前后处理都没变，结果是v2跟踪是对的，v3的跟踪很乱，结果明显不对。
> 
> 大佬， v3部署的时候，还有其他要注意的地方吗？

@pxEkin 你好，请问数据集前处理代码能分享一下吗？ @HonglinChu 提供的百度云链接失效了，感谢

**Comment by HonglinChu** [comment]
> 

@y5300 C++代码后处理大致扫了一下，确实没看到哪一步还需要改。如果模型输出没问题，可以再继续单步调试对比V2和V3后处理代码在哪一步数据异常。

**Comment by pxEkin** [comment]
> > 
> 
> @y5300 C++代码后处理大致扫了一下，确实没看到哪一步还需要改。如果模型输出没问题，可以再继续单步调试对比V2和V3后处理代码在哪一步数据异常。

我看了后处理代码， python和c++有些不一样，比如create_grids函数：
![image](https://user-images.githubusercontent.com/40013733/223109052-8ce79b00-649d-4188-8710-2929c030d416.png)
![image](https://user-images.githubusercontent.com/40013733/223109226-9e65157c-5fb7-4e49-88b4-26ee5071fb73.png)

@y5300  给个邮箱

**Comment by y5300** [comment]
> 
看到作者已更新链接，谢谢！

**Comment by pxEkin** [comment]
修改后处理代码就可以了  现在结果都对了， 就是还有点抖， 我再看看，这个issue先关了

**Comment by pxEkin** [comment]
对比了下 v2 和 v3， 说说我的对比结果：
1.抖动情况：v3比v2稳定了不少
2.对于运动比较快的目标(突然速度变快的情况)：v3的跟随性没有v2好，对于这种case，感觉v3有滞后感
3. v3比v2更容易跟丢
总体感觉，虽然v3在开源数据集上表现比v2好不少，但是从效果上来看，除了跟踪框更稳定外，没有比v2提升多少，一些情况下还不如v2的效果。

**Comment by hito0512** [comment]
@pxEkin 你好，我想问下v3训练完后，跟踪框的大小一直保持不变，抖动也比较厉害。这个要修改哪些参数呢？目前这个跟踪效果比siamfc++ alexnet版还差，v2还没有做测试

**Comment by pxEkin** [comment]
> @pxEkin 你好，我想问下v3训练完后，跟踪框的大小一直保持不变，抖动也比较厉害。这个要修改哪些参数呢？目前这个跟踪效果比siamfc++ alexnet版还差，v2还没有做测试

我没有训练v3，  我是直接用预训练模型测试的

**Comment by yifanya** [comment]
> @pxEkin 你好，我想问下v3训练完后，跟踪框的大小一直保持不变，抖动也比较厉害。这个要修改哪些参数呢？目前这个跟踪效果比siamfc++ alexnet版还差，v2还没有做测试

你好，请教下你的nanoTrackv3训练完后在VOT2018上能不能达到作者给的0.449精确度。如果能的话想请教下你是怎么训练的。我这边复现不出来😭

**Comment by Sherlock-hh** [comment]
> > V1和V2没有使用depthwise操作，V3在做相关操作的时候结合了depthwise 和pointwise两种方式（depthwise转换ncnn可能会不支持，之前尝试转换但是失败了，不清楚现在ncnn是否支持了）。模型转换过程可能没有明显报错，但在c++推理的时候网络输出值仍然异常，建议你debug查看一下转换之后的ncnn模型的输出数据。
> 
> 额 看了下，是模型转换出错了，，

你好你好，请问您这边的转ncnn的过程是怎样转换的呢？我这边一直ncnn的结果一直不正确

**Comment by Sherlock-hh** [comment]
> +代码后处理大致扫了一下，确实没看到哪一步还需要改。如果模型输出没问题，可以再继续单步调试对比V2和V3后处理代码在哪一步数据异常。

你好你好，我看了您的修改，是除了score_size和WINDOW_INFLUENCE: 0.455 PENALTY_K: 0.138 LR: 0.348，还需要修改其他部分吗？

**Comment by CV-poo** [comment]
> 对比了下 v2 和 v3， 说说我的对比结果： 1.抖动情况：v3比v2稳定了不少 2.对于运动比较快的目标(突然速度变快的情况)：v3的跟随性没有v2好，对于这种case，感觉v3有滞后感 3. v3比v2更容易跟丢 总体感觉，虽然v3在开源数据集上表现比v2好不少，但是从效果上来看，除了跟踪框更稳定外，没有比v2提升多少，一些情况下还不如v2的效果。

@pxEkin 您好大佬，请问您nanotrackv3的c++版本的后处理代码除了修改了score-size为15，以及产生网格点的方式与python中相同，还有后处理坐标映射时与python的demo相同，还修改了什么呀，我这边还没有对齐结果，肯定大佬的帮助，谢谢您

**Comment by NewboySoCool** [comment]
> V1的效果确实会差一些，V3的也马上要出来了，可以体验一下

V3版本量化之后 ，还会抖的厉害吗？
