### ISSUE TITLE
大佬您好，crop GOT-10的网盘链接https://pan.baidu.com/s/1ouqVMVAsLtXDWeanPYTkHw password: owlo失效了，可以劳烦您更新一下嘛

### ISSUE THREAD

**Issue by bestzsq** [HonglinChu/SiamTrackers#94]

**Comment by bestzsq** [comment]
还有个问题想请教一下大佬，关于如何得到crop511以及train.json文件夹，是通过https://github.com/STVIR/pysot/tree/master/training_dataset/vid中类似的脚本实现的嘛？

**Comment by HonglinChu** [comment]
Try this 链接: https://pan.baidu.com/s/1yzXnRUqjreSeojEQOmluQg 提取码: un47 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by bestzsq** [comment]
非常感谢~
