### ISSUE TITLE
nanotrackv3训练过程中各项loss均为nan

### ISSUE THREAD

**Issue by Duranin** [HonglinChu/SiamTrackers#95]
您好，我未更改v3的网络，在训练过程中各项loss均为nan，请问您知道如何解决吗？

**Comment by Duranin** [comment]
更准确的说，在DepthwiseXCorr的前向传播过程中，kernel和search两项数据在通过self.conv_kernel和self.conv_search后均变为了nan

**Comment by bestzsq** [comment]
单卡也遇到相同的问题，学习率减小没有效果

**Comment by bestzsq** [comment]
@Duranin 请问一下v3 nan的问题您这边解决掉了嘛?

**Comment by Duranin** [comment]
单卡情况下，把warmup的学习改大就行。个人感觉原因是模型初始化的时候有不少数据赋值是0，学习率小导致出现了除0的问题，loss就变成nan了。

**Comment by hito0512** [comment]
我也遇到了这个问题，在训练的时候， TRAIN下的 PRETRAINED 设置为nanotrackv3.pth就可以解决了，应该是网络初始化没有做好

**Comment by Z-Xiong** [comment]
https://github.com/HonglinChu/SiamTrackers/blob/805208b5348346d35e64abcbe901a3829743e157/NanoTrack/nanotrack/models/model_builder.py#L35
在这里添加初始化权重代码就可以解决了：

```
    # Initialize weights
    self.init_weights()
        
    @torch.no_grad()
    def init_weights(self):
        def _init(m):
            if isinstance(m, nn.Conv2d):
                nn.init.normal_(m.weight, mean=0, std=0.5)
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.ones_(m.weight)
                nn.init.zeros_(m.bias)
            elif isinstance(m, nn.Linear):
                nn.init.uniform_(m.weight, a=-0.1, b=0.1)
                m.bias.data.fill_(0.01)
        self.apply(_init)
```
