### ISSUE TITLE
Nanotrack How To Crop Data

### ISSUE THREAD

**Issue by notsmartpig** [HonglinChu/SiamTrackers#97]
大佬你好，在NanoTrack中 how to crop Got10K 的百度网盘链接已经失效了，而且pysot似乎没有提供got的裁剪代码，那么如何生成train.json和crop511呢？能否麻烦您再分享一个有效链接呢，十分感谢！

**Comment by HonglinChu** [comment]
链接: https://pan.baidu.com/s/1F6XASBwFHUln0tCOD68OUQ?pwd=3dua 提取码: 3dua

**Comment by HonglinChu** [comment]
https://drive.google.com/file/d/1VwTAAiiT4gZVUVkoHSMV3vRJATrBSOIz/view?usp=sharing
