### ISSUE TITLE
nanotrackv3 跟踪框一直保持固定

### ISSUE THREAD

**Issue by hito0512** [HonglinChu/SiamTrackers#98]
用训练好的nanotrackv3进行测试，发现跟踪框的大小几乎一致保持不变，不会随着物体的大小改变而改变，而且精度也很低。请问需要设置哪里吗？代码正在梳理当中

**Comment by pxEkin** [comment]
> 用训练好的nanotrackv3进行测试，发现跟踪框的大小几乎一致保持不变，不会随着物体的大小改变而改变，而且精度也很低。请问需要设置哪里吗？代码正在梳理当中

你用什么代码测试的，，python的话，没什么问题。  如果用之前作者给的c++ demo，那么需要改一些东西的。

我测试了v3，总体上感觉没有v2好用。

**Comment by hito0512** [comment]
我是用python测试的，模型是我自己训练的，但是结果不是很好，不稳定，精度也不是很高

**Comment by pxEkin** [comment]
> 我是用python测试的，模型是我自己训练的，但是结果不是很好，不稳定，精度也不是很高

你的问题解决了吗

**Comment by hito0512** [comment]
> > 我是用python测试的，模型是我自己训练的，但是结果不是很好，不稳定，精度也不是很高
> 
> 你的问题解决了吗

没有，用自带的v2和v3模型测试了下demo[girl dance视频]，发现这个跟踪结果也不是很好

**Comment by pxEkin** [comment]
> > > 我是用python测试的，模型是我自己训练的，但是结果不是很好，不稳定，精度也不是很高
> > 
> > 
> > 你的问题解决了吗
> 
> 没有，用自带的v2和v3模型测试了下demo[girl dance视频]，发现这个跟踪结果也不是很好

发现 v3 的跟踪结果不是很好？   我的测试结果是v3没有v2好，但是v2的框更抖些

**Comment by hito0512** [comment]
> > > > 我是用python测试的，模型是我自己训练的，但是结果不是很好，不稳定，精度也不是很高
> > > 
> > > 
> > > 你的问题解决了吗
> > 
> > 
> > 没有，用自带的v2和v3模型测试了下demo[girl dance视频]，发现这个跟踪结果也不是很好
> 
> 发现 v3 的跟踪结果不是很好？ 我的测试结果是v3没有v2好，但是v2的框更抖些

两个跟踪结果都不是很好

**Comment by pxEkin** [comment]
> > > > > 我是用python测试的，模型是我自己训练的，但是结果不是很好，不稳定，精度也不是很高
> > > > 
> > > > 
> > > > 你的问题解决了吗
> > > 
> > > 
> > > 没有，用自带的v2和v3模型测试了下demo[girl dance视频]，发现这个跟踪结果也不是很好
> > 
> > 
> > 发现 v3 的跟踪结果不是很好？ 我的测试结果是v3没有v2好，但是v2的框更抖些
> 
> 两个跟踪结果都不是很好

哦哦  lightTrack稳定，你可以试试，    就是速度慢不少，手机上实时不了

**Comment by y5300** [comment]
lightTrack有训练代码吗？ @pxEkin

**Comment by pxEkin** [comment]
> lightTrack有训练代码吗？ @pxEkin

没有

**Comment by hito0512** [comment]
> > > > > > 我是用python测试的，模型是我自己训练的，但是结果不是很好，不稳定，精度也不是很高
> > > > > 
> > > > > 
> > > > > 你的问题解决了吗
> > > > 
> > > > 
> > > > 没有，用自带的v2和v3模型测试了下demo[girl dance视频]，发现这个跟踪结果也不是很好
> > > 
> > > 
> > > 发现 v3 的跟踪结果不是很好？ 我的测试结果是v3没有v2好，但是v2的框更抖些
> > 
> > 
> > 两个跟踪结果都不是很好
> 
> 哦哦 lightTrack稳定，你可以试试， 就是速度慢不少，手机上实时不了

没有训练代码，就不做测试了

**Comment by hito0512** [comment]
@pxEkin 发现调整 WINDOW_INFLUENCE 可以改善一下跟踪框保持不变的问题，但是没有彻底解决

**Comment by xingxinghanzi** [comment]
> > 用训练好的nanotrackv3进行测试，发现跟踪框的大小几乎一致保持不变，不会随着物体的大小改变而改变，而且精度也很低。请问需要设置哪里吗？代码正在梳理当中
> 
> 你用什么代码测试的，，python的话，没什么问题。 如果用之前作者给的c++ demo，那么需要改一些东西的。
> 
> 我测试了v3，总体上感觉没有v2好用。

您好， 请问你改了哪部分代码？你是转的ncnn模型还是其他呀

**Comment by Sherlock-hh** [comment]
> > 用训练好的nanotrackv3进行测试，发现跟踪框的大小几乎一致保持不变，不会随着物体的大小改变而改变，而且精度也很低。请问需要设置哪里吗？代码正在梳理当中
> 
> 你用什么代码测试的，，python的话，没什么问题。 如果用之前作者给的c++ demo，那么需要改一些东西的。
> 
> 我测试了v3，总体上感觉没有v2好用。

你好，请问c++代码是修改了哪部分呢？我按照作者提示修改了cfg中的3个参数，除此之外还有其他地方需要修改吗？

**Comment by NewboySoCool** [comment]
> > > > 我是用python测试的，模型是我自己训练的，但是结果不是很好，不稳定，精度也不是很高
> > > 
> > > 
> > > 你的问题解决了吗
> > 
> > 
> > 没有，用自带的v2和v3模型测试了下demo[girl dance视频]，发现这个跟踪结果也不是很好
> 
> 发现 v3 的跟踪结果不是很好？ 我的测试结果是v3没有v2好，但是v2的框更抖些

能解决吗？ python上v3， 框一直固定怎么回事呢？
